/* generated by tools/gen-readers.js from data/readers/*.md — do not hand-edit.
   Public-domain texts from Aozora Bunko, verbatim; ruby converted from 《》 to <ruby>. */
window.YOMIMONO_LIBRARY = [
 {
  "id": "momotaro-peach-boy",
  "authentic": true,
  "band": "authentic",
  "moves": {},
  "quick": [],
  "evidence": [],
  "title": "桃太郎",
  "en": "Momotarō (Peach Boy)",
  "author": "楠山正雄 (d. 1950-11-26)",
  "translator": "",
  "died": "1950-11-26",
  "card": "https://www.aozora.gr.jp/cards/000329/card18376.html",
  "orthography": "新字新仮名",
  "beyond": [
   "〜であります／〜でありました (formal narrative copula)",
   "classical-flavoured set phrases in narration (e.g. 「〜のであります」), otherwise modern grammar throughout"
  ],
  "attribution": [
   "底本：「日本の神話と十大昔話」講談社学術文庫、講談社",
   "1983（昭和58）年5月10日第1刷発行",
   "1992（平成4）年4月20日第14刷発行",
   "※「そのお城《しろ》のいちばん高《たか》い」「こうして何年《なんねん》も」の行頭が下がっていないのは底本のままです。",
   "入力：鈴木厚司",
   "校正：大久保ゆう",
   "2003年8月27日作成",
   "2013年10月21日修正",
   "青空文庫作成ファイル：",
   "このファイルは、インターネットの図書館、青空文庫（http://www.aozora.gr.jp/）で作られました。入力、校正、制作にあたったのは、ボランティアの皆さんです。"
  ],
  "chapters": [
   {
    "t": "第一章",
    "en": "The Peach on the River",
    "from": 0,
    "to": 54
   },
   {
    "t": "第二章",
    "en": "Momotarō Sets Out",
    "from": 55,
    "to": 96
   },
   {
    "t": "第三章",
    "en": "Three Companions",
    "from": 97,
    "to": 154
   },
   {
    "t": "第四章",
    "en": "The Battle for Ogre Island",
    "from": 155,
    "to": 198
   }
  ],
  "sentences": [
   "むかし、むかし、あるところに、おじいさんとおばあさんがありました。",
   "まいにち、おじいさんは山へしば<ruby>刈<rt>か</rt></ruby>りに、おばあさんは川へ<ruby>洗濯<rt>せんたく</rt></ruby>に行きました。",
   "ある日、おばあさんが、川のそばで、せっせと<ruby>洗濯<rt>せんたく</rt></ruby>をしていますと、<ruby>川上<rt>かわかみ</rt></ruby>から、大きな<ruby>桃<rt>もも</rt></ruby>が一つ、",
   "「ドンブラコッコ、スッコッコ。",
   "ドンブラコッコ、スッコッコ。」",
   "と<ruby>流<rt>なが</rt></ruby>れて<ruby>来<rt>き</rt></ruby>ました。",
   "「おやおや、これはみごとな<ruby>桃<rt>もも</rt></ruby>だこと。",
   "おじいさんへのおみやげに、どれどれ、うちへ<ruby>持<rt>も</rt></ruby>って<ruby>帰<rt>かえ</rt></ruby>りましょう。」",
   "おばあさんは、そう<ruby>言<rt>い</rt></ruby>いながら、<ruby>腰<rt>こし</rt></ruby>をかがめて<ruby>桃<rt>もも</rt></ruby>を<ruby>取<rt>と</rt></ruby>ろうとしましたが、<ruby>遠<rt>とお</rt></ruby>くって手がとどきません。",
   "おばあさんはそこで、",
   "「あっちの<ruby>水<rt>みいず</rt></ruby>は、かあらいぞ。",
   "こっちの<ruby>水<rt>みいず</rt></ruby>は、ああまいぞ。",
   "かあらい<ruby>水<rt>みいず</rt></ruby>は、よけて<ruby>来<rt>こ</rt></ruby>い。",
   "ああまい<ruby>水<rt>みいず</rt></ruby>に、よって<ruby>来<rt>こ</rt></ruby>い。",
   "と<ruby>歌<rt>うた</rt></ruby>いながら、手をたたきました。",
   "すると<ruby>桃<rt>もも</rt></ruby>はまた、",
   "「ドンブラコッコ、スッコッコ。",
   "ドンブラコッコ、スッコッコ。」",
   "といいながら、おばあさんの<ruby>前<rt>まえ</rt></ruby>へ<ruby>流<rt>なが</rt></ruby>れて<ruby>来<rt>き</rt></ruby>ました。",
   "おばあさんはにこにこしながら、",
   "「<ruby>早<rt>はや</rt></ruby>くおじいさんと<ruby>二人<rt>ふたり</rt></ruby>で<ruby>分<rt>わ</rt></ruby>けて<ruby>食<rt>た</rt></ruby>べましょう。」",
   "と<ruby>言<rt>い</rt></ruby>って、<ruby>桃<rt>もも</rt></ruby>をひろい<ruby>上<rt>あ</rt></ruby>げて、<ruby>洗濯物<rt>せんたくもの</rt></ruby>といっしょにたらいの中に<ruby>入<rt>い</rt></ruby>れて、えっちら、おっちら、かかえておうちへ<ruby>帰<rt>かえ</rt></ruby>りました。",
   "<ruby>夕方<rt>ゆうがた</rt></ruby>になってやっと、おじいさんは山からしばを<ruby>背負<rt>せお</rt></ruby>って<ruby>帰<rt>かえ</rt></ruby>って<ruby>来<rt>き</rt></ruby>ました。",
   "「おばあさん、<ruby>今<rt>いま</rt></ruby><ruby>帰<rt>かえ</rt></ruby>ったよ。」",
   "「おや、おじいさん、おかいんなさい。",
   "<ruby>待<rt>ま</rt></ruby>っていましたよ。",
   "さあ、<ruby>早<rt>はや</rt></ruby>くお<ruby>上<rt>あ</rt></ruby>がんなさい。",
   "いいものを<ruby>上<rt>あ</rt></ruby>げますから。」",
   "「それはありがたいな。",
   "<ruby>何<rt>なん</rt></ruby>だね、そのいいものというのは。」",
   "こういいながら、おじいさんはわらじをぬいで、上に<ruby>上<rt>あ</rt></ruby>がりました。",
   "その<ruby>間<rt>ま</rt></ruby>に、おばあさんは<ruby>戸棚<rt>とだな</rt></ruby>の中からさっきの<ruby>桃<rt>もも</rt></ruby>を<ruby>重<rt>おも</rt></ruby>そうにかかえて<ruby>来<rt>き</rt></ruby>て、",
   "「ほら、ごらんなさいこの<ruby>桃<rt>もも</rt></ruby>を。」",
   "と<ruby>言<rt>い</rt></ruby>いました。",
   "「ほほう、これはこれは。",
   "どこからこんなみごとな<ruby>桃<rt>もも</rt></ruby>を<ruby>買<rt>か</rt></ruby>って<ruby>来<rt>き</rt></ruby>た。」",
   "「いいえ、<ruby>買<rt>か</rt></ruby>って<ruby>来<rt>き</rt></ruby>たのではありません。",
   "<ruby>今日<rt>きょう</rt></ruby>川で<ruby>拾<rt>ひろ</rt></ruby>って<ruby>来<rt>き</rt></ruby>たのですよ。」",
   "「え、なに、川で<ruby>拾<rt>ひろ</rt></ruby>って<ruby>来<rt>き</rt></ruby>た。",
   "それはいよいよめずらしい。」",
   "こうおじいさんは<ruby>言<rt>い</rt></ruby>いながら、<ruby>桃<rt>もも</rt></ruby>を<ruby>両手<rt>りょうて</rt></ruby>にのせて、ためつ、すがめつ、ながめていますと、だしぬけに、<ruby>桃<rt>もも</rt></ruby>はぽんと中から二つに<ruby>割<rt>わ</rt></ruby>れて、",
   "「おぎゃあ、おぎゃあ。」",
   "と<ruby>勇<rt>いさ</rt></ruby>ましいうぶ<ruby>声<rt>こえ</rt></ruby>を<ruby>上<rt>あ</rt></ruby>げながら、かわいらしい<ruby>赤<rt>あか</rt></ruby>さんが<ruby>元気<rt>げんき</rt></ruby>よくとび<ruby>出<rt>だ</rt></ruby>しました。",
   "「おやおや、まあ。」",
   "おじいさんも、おばあさんも、びっくりして、<ruby>二人<rt>ふたり</rt></ruby>いっしょに<ruby>声<rt>こえ</rt></ruby>を<ruby>立<rt>た</rt></ruby>てました。",
   "「まあまあ、わたしたちが、へいぜい、どうかして<ruby>子供<rt>こども</rt></ruby>が<ruby>一人<rt>ひとり</rt></ruby>ほしい、ほしいと<ruby>言<rt>い</rt></ruby>っていたものだから、きっと<ruby>神<rt>かみ</rt></ruby>さまがこの子をさずけて<ruby>下<rt>くだ</rt></ruby>さったにちがいない。」",
   "おじいさんも、おばあさんも、うれしがって、こう<ruby>言<rt>い</rt></ruby>いました。",
   "そこであわてておじいさんがお<ruby>湯<rt>ゆ</rt></ruby>をわかすやら、おばあさんがむつきをそろえるやら、<ruby>大<rt>おお</rt></ruby>さわぎをして、<ruby>赤<rt>あか</rt></ruby>さんを<ruby>抱<rt>だ</rt></ruby>き<ruby>上<rt>あ</rt></ruby>げて、うぶ<ruby>湯<rt>ゆ</rt></ruby>をつかわせました。",
   "するといきなり、",
   "「うん。」",
   "と<ruby>言<rt>い</rt></ruby>いながら、<ruby>赤<rt>あか</rt></ruby>さんは<ruby>抱<rt>だ</rt></ruby>いているおばあさんの手をはねのけました。",
   "「おやおや、<ruby>何<rt>なん</rt></ruby>という<ruby>元気<rt>げんき</rt></ruby>のいい子だろう。」",
   "おじいさんとおばあさんは、こう<ruby>言<rt>い</rt></ruby>って<ruby>顔<rt>かお</rt></ruby>を<ruby>見合<rt>みあ</rt></ruby>わせながら、「あッは、あッは。」",
   "とおもしろそうに<ruby>笑<rt>わら</rt></ruby>いました。",
   "そして<ruby>桃<rt>もも</rt></ruby>の中から<ruby>生<rt>う</rt></ruby>まれた子だというので、この子に<ruby>桃太郎<rt>ももたろう</rt></ruby>という<ruby>名<rt>な</rt></ruby>をつけました。",
   "おじいさんとおばあさんは、それはそれはだいじにして<ruby>桃太郎<rt>ももたろう</rt></ruby>を<ruby>育<rt>そだ</rt></ruby>てました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>はだんだん<ruby>成長<rt>せいちょう</rt></ruby>するにつれて、あたりまえの<ruby>子供<rt>こども</rt></ruby>にくらべては、ずっと<ruby>体<rt>からだ</rt></ruby>も大きいし、<ruby>力<rt>ちから</rt></ruby>がばかに<ruby>強<rt>つよ</rt></ruby>くって、すもうをとっても<ruby>近所<rt>きんじょ</rt></ruby>の<ruby>村<rt>むら</rt></ruby>じゅうで、かなうものは<ruby>一人<rt>ひとり</rt></ruby>もないくらいでしたが、そのくせ<ruby>気<rt>き</rt></ruby>だてはごくやさしくって、おじいさんとおばあさんによく<ruby>孝行<rt>こうこう</rt></ruby>をしました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>は十五になりました。",
   "もうそのじぶんには、<ruby>日本<rt>にほん</rt></ruby>の<ruby>国中<rt>くにじゅう</rt></ruby>で、<ruby>桃太郎<rt>ももたろう</rt></ruby>ほど<ruby>強<rt>つよ</rt></ruby>いものはないようになりました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>はどこか<ruby>外国<rt>がいこく</rt></ruby>へ出かけて、<ruby>腕<rt>うで</rt></ruby>いっぱい、<ruby>力<rt>ちから</rt></ruby>だめしをしてみたくなりました。",
   "するとそのころ、ほうぼう<ruby>外国<rt>がいこく</rt></ruby>の<ruby>島々<rt>しまじま</rt></ruby>をめぐって<ruby>帰<rt>かえ</rt></ruby>って<ruby>来<rt>き</rt></ruby>た人があって、いろいろめずらしい、ふしぎなお<ruby>話<rt>はなし</rt></ruby>をした<ruby>末<rt>すえ</rt></ruby>に、",
   "「もう<ruby>何年<rt>なんねん</rt></ruby>も<ruby>何年<rt>なんねん</rt></ruby>も<ruby>船<rt>ふね</rt></ruby>をこいで行くと、<ruby>遠<rt>とお</rt></ruby>い<ruby>遠<rt>とお</rt></ruby>い<ruby>海<rt>うみ</rt></ruby>のはてに、<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>という<ruby>所<rt>ところ</rt></ruby>がある。",
   "<ruby>悪<rt>わる</rt></ruby>い<ruby>鬼<rt>おに</rt></ruby>どもが、いかめしいくろがねのお<ruby>城<rt>しろ</rt></ruby>の中に<ruby>住<rt>す</rt></ruby>んで、ほうぼうの<ruby>国<rt>くに</rt></ruby>からかすめ<ruby>取<rt>と</rt></ruby>った<ruby>貴<rt>とうと</rt></ruby>い<ruby>宝物<rt>たからもの</rt></ruby>を<ruby>守<rt>まも</rt></ruby>っている。」",
   "と<ruby>言<rt>い</rt></ruby>いました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>はこの<ruby>話<rt>はなし</rt></ruby>をきくと、その<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>へ行ってみたくって、もう<ruby>居<rt>い</rt></ruby>ても<ruby>立<rt>た</rt></ruby>ってもいられなくなりました。",
   "そこでうちへ<ruby>帰<rt>かえ</rt></ruby>るとさっそく、おじいさんの<ruby>前<rt>まえ</rt></ruby>へ出て、",
   "「どうぞ、わたくしにしばらくおひまを<ruby>下<rt>くだ</rt></ruby>さい。」",
   "と<ruby>言<rt>い</rt></ruby>いました。",
   "おじいさんはびっくりして、",
   "「お<ruby>前<rt>まえ</rt></ruby>どこへ行くのだ。」",
   "と<ruby>聞<rt>き</rt></ruby>きました。",
   "「<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>へ<ruby>鬼<rt>おに</rt></ruby>せいばつに行こうと<ruby>思<rt>おも</rt></ruby>います。」",
   "と<ruby>桃太郎<rt>ももたろう</rt></ruby>はこたえました。",
   "「ほう、それはいさましいことだ。",
   "じゃあ行っておいで。」",
   "とおじいさんは<ruby>言<rt>い</rt></ruby>いました。",
   "「まあ、そんな<ruby>遠方<rt>えんぽう</rt></ruby>へ行くのでは、さぞおなかがおすきだろう。",
   "よしよし、おべんとうをこしらえて<ruby>上<rt>あ</rt></ruby>げましょう。」",
   "とおばあさんも<ruby>言<rt>い</rt></ruby>いました。",
   "そこで、おじいさんとおばあさんは、お<ruby>庭<rt>にわ</rt></ruby>のまん中に、えんやら、えんやら、大きな<ruby>臼<rt>うす</rt></ruby>を<ruby>持<rt>も</rt></ruby>ち<ruby>出<rt>だ</rt></ruby>して、おじいさんがきねを<ruby>取<rt>と</rt></ruby>ると、おばあさんはこねどりをして、",
   "「ぺんたらこっこ、ぺんたらこっこ。",
   "ぺんたらこっこ、ぺんたらこっこ。」",
   "と、おべんとうのきびだんごをつきはじめました。",
   "きびだんごがうまそうにでき<ruby>上<rt>あ</rt></ruby>がると、<ruby>桃太郎<rt>ももたろう</rt></ruby>のしたくもすっかりでき<ruby>上<rt>あ</rt></ruby>がりました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>はお<ruby>侍<rt>さむらい</rt></ruby>の<ruby>着<rt>き</rt></ruby>るような<ruby>陣羽織<rt>じんばおり</rt></ruby>を<ruby>着<rt>き</rt></ruby>て、<ruby>刀<rt>かたな</rt></ruby>を<ruby>腰<rt>こし</rt></ruby>にさして、きびだんごの<ruby>袋<rt>ふくろ</rt></ruby>をぶら<ruby>下<rt>さ</rt></ruby>げました。",
   "そして<ruby>桃<rt>もも</rt></ruby>の<ruby>絵<rt>え</rt></ruby>のかいてある<ruby>軍扇<rt>ぐんせん</rt></ruby>を手に<ruby>持<rt>も</rt></ruby>って、",
   "「ではおとうさん、おかあさん、行ってまいります。」",
   "と<ruby>言<rt>い</rt></ruby>って、ていねいに<ruby>頭<rt>あたま</rt></ruby>を<ruby>下<rt>さ</rt></ruby>げました。",
   "「じゃあ、りっぱに<ruby>鬼<rt>おに</rt></ruby>を<ruby>退治<rt>たいじ</rt></ruby>してくるがいい。」",
   "とおじいさんは<ruby>言<rt>い</rt></ruby>いました。",
   "「<ruby>気<rt>き</rt></ruby>をつけて、けがをしないようにおしよ。」",
   "とおばあさんも<ruby>言<rt>い</rt></ruby>いました。",
   "「なに、<ruby>大丈夫<rt>だいじょうぶ</rt></ruby>です、<ruby>日本一<rt>にっぽんいち</rt></ruby>のきびだんごを<ruby>持<rt>も</rt></ruby>っているから。」",
   "と<ruby>桃太郎<rt>ももたろう</rt></ruby>は<ruby>言<rt>い</rt></ruby>って、",
   "「では、ごきげんよう。」",
   "と<ruby>元気<rt>げんき</rt></ruby>な<ruby>声<rt>こえ</rt></ruby>をのこして、<ruby>出<rt>で</rt></ruby>ていきました。",
   "おじいさんとおばあさんは、<ruby>門<rt>もん</rt></ruby>の<ruby>外<rt>そと</rt></ruby>に<ruby>立<rt>た</rt></ruby>って、いつまでも、いつまでも<ruby>見送<rt>みおく</rt></ruby>っていました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>はずんずん行きますと、大きな山の上に<ruby>来<rt>き</rt></ruby>ました。",
   "すると、<ruby>草<rt>くさ</rt></ruby>むらの中から、「ワン、ワン。」",
   "と<ruby>声<rt>こえ</rt></ruby>をかけながら、<ruby>犬<rt>いぬ</rt></ruby>が一ぴきかけて<ruby>来<rt>き</rt></ruby>ました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>がふり<ruby>返<rt>かえ</rt></ruby>ると、<ruby>犬<rt>いぬ</rt></ruby>はていねいに、おじぎをして、",
   "「<ruby>桃太郎<rt>ももたろう</rt></ruby>さん、<ruby>桃太郎<rt>ももたろう</rt></ruby>さん、どちらへおいでになります。」",
   "とたずねました。",
   "「<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>へ、<ruby>鬼<rt>おに</rt></ruby>せいばつに行くのだ。」",
   "「お<ruby>腰<rt>こし</rt></ruby>に<ruby>下<rt>さ</rt></ruby>げたものは、<ruby>何<rt>なん</rt></ruby>でございます。」",
   "「<ruby>日本<rt>にっぽん</rt></ruby>一のきびだんごさ。」",
   "「一つ<ruby>下<rt>くだ</rt></ruby>さい、お<ruby>供<rt>とも</rt></ruby>しましょう。」",
   "「よし、よし、やるから、ついて<ruby>来<rt>こ</rt></ruby>い。」",
   "<ruby>犬<rt>いぬ</rt></ruby>はきびだんごを一つもらって、<ruby>桃太郎<rt>ももたろう</rt></ruby>のあとから、ついて行きました。",
   "山を<ruby>下<rt>お</rt></ruby>りてしばらく<ruby>行<rt>い</rt></ruby>くと、こんどは<ruby>森<rt>もり</rt></ruby>の中にはいりました。",
   "すると木の上から、「キャッ、キャッ。」",
   "とさけびながら、<ruby>猿<rt>さる</rt></ruby>が一ぴき、かけ<ruby>下<rt>お</rt></ruby>りて<ruby>来<rt>き</rt></ruby>ました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>がふり<ruby>返<rt>かえ</rt></ruby>ると、<ruby>猿<rt>さる</rt></ruby>はていねいに、おじぎをして、",
   "「<ruby>桃太郎<rt>ももたろう</rt></ruby>さん、<ruby>桃太郎<rt>ももたろう</rt></ruby>さん、どちらへおいでになります。」",
   "とたずねました。",
   "「<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>へ<ruby>鬼<rt>おに</rt></ruby>せいばつに行くのだ。」",
   "「お<ruby>腰<rt>こし</rt></ruby>に<ruby>下<rt>さ</rt></ruby>げたものは、<ruby>何<rt>なん</rt></ruby>でございます。」",
   "「<ruby>日本<rt>にっぽん</rt></ruby>一のきびだんごさ。」",
   "「一つ<ruby>下<rt>くだ</rt></ruby>さい、お<ruby>供<rt>とも</rt></ruby>しましょう。」",
   "「よし、よし、やるから、ついて<ruby>来<rt>こ</rt></ruby>い。」",
   "<ruby>猿<rt>さる</rt></ruby>もきびだんごを一つもらって、あとからついて行きました。",
   "山を<ruby>下<rt>お</rt></ruby>りて、<ruby>森<rt>もり</rt></ruby>をぬけて、こんどはひろい<ruby>野原<rt>のはら</rt></ruby>へ出ました。",
   "すると<ruby>空<rt>そら</rt></ruby>の上で、「ケン、ケン。」",
   "と<ruby>鳴<rt>な</rt></ruby>く<ruby>声<rt>こえ</rt></ruby>がして、きじが一<ruby>羽<rt>わ</rt></ruby>とんで<ruby>来<rt>き</rt></ruby>ました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>がふり<ruby>返<rt>かえ</rt></ruby>ると、きじはていねいに、おじぎをして、",
   "「<ruby>桃太郎<rt>ももたろう</rt></ruby>さん、<ruby>桃太郎<rt>ももたろう</rt></ruby>さん、どちらへおいでになります。」",
   "とたずねました。",
   "「<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>へ<ruby>鬼<rt>おに</rt></ruby>せいばつに行くのだ。」",
   "「お<ruby>腰<rt>こし</rt></ruby>に<ruby>下<rt>さ</rt></ruby>げたものは、<ruby>何<rt>なん</rt></ruby>でございます。」",
   "「<ruby>日本一<rt>にっぽんいち</rt></ruby>のきびだんごさ。」",
   "「一つ<ruby>下<rt>くだ</rt></ruby>さい、お<ruby>供<rt>とも</rt></ruby>しましょう。」",
   "「よし、よし、やるから、ついて<ruby>来<rt>こ</rt></ruby>い。」",
   "きじもきびだんごを一つもらって、<ruby>桃太郎<rt>ももたろう</rt></ruby>のあとからついて行きました。",
   "<ruby>犬<rt>いぬ</rt></ruby>と、<ruby>猿<rt>さる</rt></ruby>と、きじと、これで三にんまで、いい<ruby>家来<rt>けらい</rt></ruby>ができたので、<ruby>桃太郎<rt>ももたろう</rt></ruby>はいよいよ<ruby>勇<rt>いさ</rt></ruby>み<ruby>立<rt>た</rt></ruby>って、またずんずん<ruby>進<rt>すす</rt></ruby>んで行きますと、やがてひろい<ruby>海<rt>うみ</rt></ruby>ばたに出ました。",
   "そこには、ちょうどいいぐあいに、<ruby>船<rt>ふね</rt></ruby>が一そうつないでありました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>と、三にんの<ruby>家来<rt>けらい</rt></ruby>は、さっそく、この<ruby>船<rt>ふね</rt></ruby>に<ruby>乗<rt>の</rt></ruby>り<ruby>込<rt>こ</rt></ruby>みました。",
   "「わたくしは、<ruby>漕<rt>こ</rt></ruby>ぎ<ruby>手<rt>て</rt></ruby>になりましょう。」",
   "こう<ruby>言<rt>い</rt></ruby>って、<ruby>犬<rt>いぬ</rt></ruby>は<ruby>船<rt>ふね</rt></ruby>をこぎ<ruby>出<rt>だ</rt></ruby>しました。",
   "「わたくしは、かじ<ruby>取<rt>と</rt></ruby>りになりましょう。」",
   "こう<ruby>言<rt>い</rt></ruby>って、<ruby>猿<rt>さる</rt></ruby>がかじに<ruby>座<rt>すわ</rt></ruby>りました。",
   "「わたくしは<ruby>物見<rt>ものみ</rt></ruby>をつとめましょう。」",
   "こう<ruby>言<rt>い</rt></ruby>って、きじがへさきに<ruby>立<rt>た</rt></ruby>ちました。",
   "うららかないいお<ruby>天気<rt>てんき</rt></ruby>で、まっ<ruby>青<rt>さお</rt></ruby>な<ruby>海<rt>うみ</rt></ruby>の上には、<ruby>波<rt>なみ</rt></ruby>一つ<ruby>立<rt>た</rt></ruby>ちませんでした。",
   "<ruby>稲妻<rt>いなづま</rt></ruby>が<ruby>走<rt>はし</rt></ruby>るようだといおうか、<ruby>矢<rt>や</rt></ruby>を<ruby>射<rt>い</rt></ruby>るようだといおうか、目のまわるような<ruby>速<rt>はや</rt></ruby>さで<ruby>船<rt>ふね</rt></ruby>は走って行きました。",
   "ほんの一<ruby>時間<rt>じかん</rt></ruby>も<ruby>走<rt>はし</rt></ruby>ったと<ruby>思<rt>おも</rt></ruby>うころ、へさきに<ruby>立<rt>た</rt></ruby>って<ruby>向<rt>む</rt></ruby>こうをながめていたきじが、「あれ、あれ、<ruby>島<rt>しま</rt></ruby>が。」",
   "とさけびながら、ぱたぱたと<ruby>高<rt>たか</rt></ruby>い<ruby>羽音<rt>はおと</rt></ruby>をさせて、<ruby>空<rt>そら</rt></ruby>にとび<ruby>上<rt>あ</rt></ruby>がったと<ruby>思<rt>おも</rt></ruby>うと、スウッとまっすぐに<ruby>風<rt>かぜ</rt></ruby>を<ruby>切<rt>き</rt></ruby>って、<ruby>飛<rt>と</rt></ruby>んでいきました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>もすぐきじの<ruby>立<rt>た</rt></ruby>ったあとから<ruby>向<rt>む</rt></ruby>こうを<ruby>見<rt>み</rt></ruby>ますと、なるほど、<ruby>遠<rt>とお</rt></ruby>い<ruby>遠<rt>とお</rt></ruby>い<ruby>海<rt>うみ</rt></ruby>のはてに、ぼんやり<ruby>雲<rt>くも</rt></ruby>のような<ruby>薄<rt>うす</rt></ruby>ぐろいものが<ruby>見<rt>み</rt></ruby>えました。",
   "<ruby>船<rt>ふね</rt></ruby>の<ruby>進<rt>すす</rt></ruby>むにしたがって、<ruby>雲<rt>くも</rt></ruby>のように<ruby>見<rt>み</rt></ruby>えていたものが、だんだんはっきりと<ruby>島<rt>しま</rt></ruby>の<ruby>形<rt>かたち</rt></ruby>になって、あらわれてきました。",
   "「ああ、<ruby>見<rt>み</rt></ruby>える、<ruby>見<rt>み</rt></ruby>える、<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>が<ruby>見<rt>み</rt></ruby>える。」",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>がこういうと、<ruby>犬<rt>いぬ</rt></ruby>も、<ruby>猿<rt>さる</rt></ruby>も、<ruby>声<rt>こえ</rt></ruby>をそろえて、「<ruby>万歳<rt>ばんざい</rt></ruby>、<ruby>万歳<rt>ばんざい</rt></ruby>。」",
   "とさけびました。",
   "<ruby>見<rt>み</rt></ruby>る<ruby>見<rt>み</rt></ruby>る<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>が<ruby>近<rt>ちか</rt></ruby>くなって、もう<ruby>硬<rt>かた</rt></ruby>い<ruby>岩<rt>いわ</rt></ruby>で<ruby>畳<rt>たた</rt></ruby>んだ<ruby>鬼<rt>おに</rt></ruby>のお<ruby>城<rt>しろ</rt></ruby>が<ruby>見<rt>み</rt></ruby>えました。",
   "いかめしいくろがねの<ruby>門<rt>もん</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>に<ruby>見<rt>み</rt></ruby>はりをしている<ruby>鬼<rt>おに</rt></ruby>の<ruby>兵隊<rt>へいたい</rt></ruby>のすがたも<ruby>見<rt>み</rt></ruby>えました。",
   "そのお<ruby>城<rt>しろ</rt></ruby>のいちばん<ruby>高<rt>たか</rt></ruby>い<ruby>屋根<rt>やね</rt></ruby>の上に、きじがとまって、こちらを<ruby>見<rt>み</rt></ruby>ていました。",
   "こうして<ruby>何年<rt>なんねん</rt></ruby>も、<ruby>何年<rt>なんねん</rt></ruby>もこいで<ruby>行<rt>い</rt></ruby>かなければならないという<ruby>鬼<rt>おに</rt></ruby>が<ruby>島<rt>しま</rt></ruby>へ、ほんの目をつぶっている<ruby>間<rt>ま</rt></ruby>に<ruby>来<rt>き</rt></ruby>たのです。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>は、<ruby>犬<rt>いぬ</rt></ruby>と<ruby>猿<rt>さる</rt></ruby>をしたがえて、<ruby>船<rt>ふね</rt></ruby>からひらりと<ruby>陸<rt>おか</rt></ruby>の上にとび<ruby>上<rt>あ</rt></ruby>がりました。",
   "<ruby>見<rt>み</rt></ruby>はりをしていた<ruby>鬼<rt>おに</rt></ruby>の<ruby>兵隊<rt>へいたい</rt></ruby>は、その<ruby>見<rt>み</rt></ruby>なれないすがたを<ruby>見<rt>み</rt></ruby>ると、びっくりして、あわてて<ruby>門<rt>もん</rt></ruby>の中に<ruby>逃<rt>に</rt></ruby>げ<ruby>込<rt>こ</rt></ruby>んで、くろがねの<ruby>門<rt>もん</rt></ruby>を<ruby>固<rt>かた</rt></ruby>くしめてしまいました。",
   "その<ruby>時<rt>とき</rt></ruby><ruby>犬<rt>いぬ</rt></ruby>は<ruby>門<rt>もん</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>に<ruby>立<rt>た</rt></ruby>って、",
   "「<ruby>日本<rt>にほん</rt></ruby>の<ruby>桃太郎<rt>ももたろう</rt></ruby>さんが、お<ruby>前<rt>まえ</rt></ruby>たちをせいばいにおいでになったのだぞ。",
   "あけろ、あけろ。」",
   "とどなりながら、ドン、ドン、<ruby>扉<rt>とびら</rt></ruby>をたたきました。",
   "<ruby>鬼<rt>おに</rt></ruby>はその<ruby>声<rt>こえ</rt></ruby>を<ruby>聞<rt>き</rt></ruby>くと、ふるえ<ruby>上<rt>あ</rt></ruby>がって、よけい<ruby>一生懸命<rt>いっしょうけんめい</rt></ruby>に、中から<ruby>押<rt>お</rt></ruby>さえていました。",
   "するときじが<ruby>屋根<rt>やね</rt></ruby>の上からとび<ruby>下<rt>お</rt></ruby>りてきて、<ruby>門<rt>もん</rt></ruby>を<ruby>押<rt>お</rt></ruby>さえている<ruby>鬼<rt>おに</rt></ruby>どもの目をつつきまわりましたから、<ruby>鬼<rt>おに</rt></ruby>はへいこうして<ruby>逃<rt>に</rt></ruby>げ<ruby>出<rt>だ</rt></ruby>しました。",
   "その<ruby>間<rt>ま</rt></ruby>に、<ruby>猿<rt>さる</rt></ruby>がするすると<ruby>高<rt>たか</rt></ruby>い<ruby>岩壁<rt>いわかべ</rt></ruby>をよじ<ruby>登<rt>のぼ</rt></ruby>っていって、ぞうさなく<ruby>門<rt>もん</rt></ruby>を中からあけました。",
   "「わあッ。」",
   "とときの<ruby>声<rt>こえ</rt></ruby>を<ruby>上<rt>あ</rt></ruby>げて、<ruby>桃太郎<rt>ももたろう</rt></ruby>の<ruby>主従<rt>しゅじゅう</rt></ruby>が、いさましくお<ruby>城<rt>しろ</rt></ruby>の中に<ruby>攻<rt>せ</rt></ruby>め<ruby>込<rt>こ</rt></ruby>んでいきますと、<ruby>鬼<rt>おに</rt></ruby>の<ruby>大将<rt>たいしょう</rt></ruby>も<ruby>大<rt>おお</rt></ruby>ぜいの<ruby>家来<rt>けらい</rt></ruby>を<ruby>引<rt>ひ</rt></ruby>き<ruby>連<rt>つ</rt></ruby>れて、<ruby>一人一人<rt>ひとりひとり</rt></ruby>、<ruby>太<rt>ふと</rt></ruby>い<ruby>鉄<rt>てつ</rt></ruby>の<ruby>棒<rt>ぼう</rt></ruby>をふりまわしながら、「おう、おう。」",
   "とさけんで、<ruby>向<rt>む</rt></ruby>かってきました。",
   "けれども、<ruby>体<rt>からだ</rt></ruby>が大きいばっかりで、いくじのない<ruby>鬼<rt>おに</rt></ruby>どもは、さんざんきじに目をつつかれた上に、こんどは<ruby>犬<rt>いぬ</rt></ruby>に<ruby>向<rt>む</rt></ruby>こうずねをくいつかれたといっては、<ruby>痛<rt>いた</rt></ruby>い、<ruby>痛<rt>いた</rt></ruby>いと<ruby>逃<rt>に</rt></ruby>げまわり、<ruby>猿<rt>さる</rt></ruby>に<ruby>顔<rt>かお</rt></ruby>を<ruby>引<rt>ひ</rt></ruby>っかかれたといっては、おいおい<ruby>泣<rt>な</rt></ruby>き<ruby>出<rt>だ</rt></ruby>して、<ruby>鉄<rt>てつ</rt></ruby>の<ruby>棒<rt>ぼう</rt></ruby>も<ruby>何<rt>なに</rt></ruby>もほうり<ruby>出<rt>だ</rt></ruby>して、<ruby>降参<rt>こうさん</rt></ruby>してしまいました。",
   "おしまいまでがまんして、たたかっていた<ruby>鬼<rt>おに</rt></ruby>の<ruby>大将<rt>たいしょう</rt></ruby>も、とうとう<ruby>桃太郎<rt>ももたろう</rt></ruby>に<ruby>組<rt>く</rt></ruby>みふせられてしまいました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>は大きな<ruby>鬼<rt>おに</rt></ruby>の<ruby>背中<rt>せなか</rt></ruby>に、<ruby>馬乗<rt>うまの</rt></ruby>りにまたがって、",
   "「どうだ、これでも<ruby>降参<rt>こうさん</rt></ruby>しないか。」",
   "といって、ぎゅうぎゅう、ぎゅうぎゅう、<ruby>押<rt>お</rt></ruby>さえつけました。",
   "<ruby>鬼<rt>おに</rt></ruby>の<ruby>大将<rt>たいしょう</rt></ruby>は、<ruby>桃太郎<rt>ももたろう</rt></ruby>の<ruby>大力<rt>だいりき</rt></ruby>で<ruby>首<rt>くび</rt></ruby>をしめられて、もう<ruby>苦<rt>くる</rt></ruby>しくってたまりませんから、<ruby>大<rt>おお</rt></ruby>つぶの<ruby>涙<rt>なみだ</rt></ruby>をぼろぼろこぼしながら、",
   "「<ruby>降参<rt>こうさん</rt></ruby>します、<ruby>降参<rt>こうさん</rt></ruby>します。",
   "<ruby>命<rt>いのち</rt></ruby>だけはお<ruby>助<rt>たす</rt></ruby>け<ruby>下<rt>くだ</rt></ruby>さい。",
   "その<ruby>代<rt>か</rt></ruby>わりに<ruby>宝物<rt>たからもの</rt></ruby>をのこらずさし<ruby>上<rt>あ</rt></ruby>げます。」",
   "こう<ruby>言<rt>い</rt></ruby>って、ゆるしてもらいました。",
   "<ruby>鬼<rt>おに</rt></ruby>の<ruby>大将<rt>たいしょう</rt></ruby>は<ruby>約束<rt>やくそく</rt></ruby>のとおり、お<ruby>城<rt>しろ</rt></ruby>から、かくれみのに、かくれ<ruby>笠<rt>がさ</rt></ruby>、うちでの<ruby>小<rt>こ</rt></ruby>づちに<ruby>如意宝珠<rt>にょいほうじゅ</rt></ruby>、そのほかさんごだの、たいまいだの、るりだの、<ruby>世界<rt>せかい</rt></ruby>でいちばん<ruby>貴<rt>とうと</rt></ruby>い<ruby>宝物<rt>たからもの</rt></ruby>を山のように<ruby>車<rt>くるま</rt></ruby>に<ruby>積<rt>つ</rt></ruby>んで<ruby>出<rt>だ</rt></ruby>しました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>はたくさんの<ruby>宝物<rt>たからもの</rt></ruby>をのこらず<ruby>積<rt>つ</rt></ruby>んで、三にんの<ruby>家来<rt>けらい</rt></ruby>といっしょに、また<ruby>船<rt>ふね</rt></ruby>に<ruby>乗<rt>の</rt></ruby>りました。",
   "<ruby>帰<rt>かえ</rt></ruby>りは行きよりもまた一そう<ruby>船<rt>ふね</rt></ruby>の<ruby>走<rt>はし</rt></ruby>るのが<ruby>速<rt>はや</rt></ruby>くって、<ruby>間<rt>ま</rt></ruby>もなく<ruby>日本<rt>にほん</rt></ruby>の<ruby>国<rt>くに</rt></ruby>に<ruby>着<rt>つ</rt></ruby>きました。",
   "<ruby>船<rt>ふね</rt></ruby>が<ruby>陸<rt>おか</rt></ruby>に<ruby>着<rt>つ</rt></ruby>きますと、<ruby>宝物<rt>たからもの</rt></ruby>をいっぱい<ruby>積<rt>つ</rt></ruby>んだ<ruby>車<rt>くるま</rt></ruby>を、<ruby>犬<rt>いぬ</rt></ruby>が<ruby>先<rt>さき</rt></ruby>に<ruby>立<rt>た</rt></ruby>って<ruby>引<rt>ひ</rt></ruby>き<ruby>出<rt>だ</rt></ruby>しました。",
   "きじが<ruby>綱<rt>つな</rt></ruby>を<ruby>引<rt>ひ</rt></ruby>いて、<ruby>猿<rt>さる</rt></ruby>があとを<ruby>押<rt>お</rt></ruby>しました。",
   "「えんやらさ、えんやらさ。」",
   "三にんは<ruby>重<rt>おも</rt></ruby>そうに、かけ<ruby>声<rt>ごえ</rt></ruby>をかけかけ<ruby>進<rt>すす</rt></ruby>んでいきました。",
   "うちではおじいさんと、おばあさんが、かわるがわる、",
   "「もう<ruby>桃太郎<rt>ももたろう</rt></ruby>が<ruby>帰<rt>かえ</rt></ruby>りそうなものだが。」",
   "と<ruby>言<rt>い</rt></ruby>い<ruby>言<rt>い</rt></ruby>い、<ruby>首<rt>くび</rt></ruby>をのばして<ruby>待<rt>ま</rt></ruby>っていました。",
   "そこへ<ruby>桃太郎<rt>ももたろう</rt></ruby>が三にんのりっぱな<ruby>家来<rt>けらい</rt></ruby>に、ぶんどりの<ruby>宝物<rt>たからもの</rt></ruby>を<ruby>引<rt>ひ</rt></ruby>かせて、さもとくいらしい<ruby>様子<rt>ようす</rt></ruby>をして<ruby>帰<rt>かえ</rt></ruby>って<ruby>来<rt>き</rt></ruby>ましたので、おじいさんもおばあさんも、目も<ruby>鼻<rt>はな</rt></ruby>もなくして<ruby>喜<rt>よろこ</rt></ruby>びました。",
   "「えらいぞ、えらいぞ、それこそ<ruby>日本一<rt>にっぽんいち</rt></ruby>だ。」",
   "とおじいさんは<ruby>言<rt>い</rt></ruby>いました。",
   "「まあ、まあ、けががなくって、<ruby>何<rt>なに</rt></ruby>よりさ。」",
   "とおばあさんは<ruby>言<rt>い</rt></ruby>いました。",
   "<ruby>桃太郎<rt>ももたろう</rt></ruby>は、その<ruby>時<rt>とき</rt></ruby><ruby>犬<rt>いぬ</rt></ruby>と<ruby>猿<rt>さる</rt></ruby>ときじの<ruby>方<rt>ほう</rt></ruby>を<ruby>向<rt>む</rt></ruby>いてこう<ruby>言<rt>い</rt></ruby>いました。",
   "「どうだ。",
   "<ruby>鬼<rt>おに</rt></ruby>せいばつはおもしろかったなあ。」",
   "<ruby>犬<rt>いぬ</rt></ruby>はワン、ワンとうれしそうにほえながら、<ruby>前足<rt>まえあし</rt></ruby>で<ruby>立<rt>た</rt></ruby>ちました。",
   "<ruby>猿<rt>さる</rt></ruby>はキャッ、キャッと<ruby>笑<rt>わら</rt></ruby>いながら、<ruby>白<rt>しろ</rt></ruby>い<ruby>歯<rt>は</rt></ruby>をむき<ruby>出<rt>だ</rt></ruby>しました。",
   "きじはケン、ケンと<ruby>鳴<rt>な</rt></ruby>きながら、くるくると<ruby>宙返<rt>ちゅうがえ</rt></ruby>りをしました。",
   "<ruby>空<rt>そら</rt></ruby>は<ruby>青々<rt>あおあお</rt></ruby>と<ruby>晴<rt>は</rt></ruby>れ<ruby>上<rt>あ</rt></ruby>がって、お<ruby>庭<rt>にわ</rt></ruby>には<ruby>桜<rt>さくら</rt></ruby>の<ruby>花<rt>はな</rt></ruby>が<ruby>咲<rt>さ</rt></ruby>き<ruby>乱<rt>みだ</rt></ruby>れていました。"
  ],
  "notebook": [
   {
    "w": "拾う",
    "read": "ひろう",
    "def": "to pick up, to find",
    "ch": 0
   },
   {
    "w": "洗濯",
    "read": "せんたく",
    "def": "washing, laundry",
    "ch": 0
   },
   {
    "w": "割れる",
    "read": "われる",
    "def": "to split open, to crack",
    "ch": 0
   },
   {
    "w": "元気",
    "read": "げんき",
    "def": "energetic, lively",
    "ch": 0
   },
   {
    "w": "声を上げる",
    "read": "こえをあげる",
    "def": "to cry out, to exclaim",
    "ch": 0
   },
   {
    "w": "神さま",
    "read": "かみさま",
    "def": "god, deity",
    "ch": 0
   },
   {
    "w": "名をつける",
    "read": "なをつける",
    "def": "to give a name",
    "ch": 0
   },
   {
    "w": "抱き上げる",
    "read": "だきあげる",
    "def": "to pick up in one's arms",
    "ch": 0
   },
   {
    "w": "育てる",
    "read": "そだてる",
    "def": "to raise, to bring up",
    "ch": 1
   },
   {
    "w": "成長する",
    "read": "せいちょうする",
    "def": "to grow up",
    "ch": 1
   },
   {
    "w": "力",
    "read": "ちから",
    "def": "strength, power",
    "ch": 1
   },
   {
    "w": "孝行",
    "read": "こうこう",
    "def": "filial devotion (being good to one's parents)",
    "ch": 1
   },
   {
    "w": "鬼が島",
    "read": "おにがしま",
    "def": "Ogre Island",
    "ch": 1
   },
   {
    "w": "退治",
    "read": "たいじ",
    "def": "defeating, subjugating (a monster/pest)",
    "ch": 1
   },
   {
    "w": "きびだんご",
    "read": "きびだんご",
    "def": "millet dumplings (the famous plot item)",
    "ch": 1
   },
   {
    "w": "見送る",
    "read": "みおくる",
    "def": "to see [someone] off",
    "ch": 1
   },
   {
    "w": "家来",
    "read": "けらい",
    "def": "retainer, follower",
    "ch": 2
   },
   {
    "w": "お供する",
    "read": "おともする",
    "def": "to accompany (a superior)",
    "ch": 2
   },
   {
    "w": "かじ取り",
    "read": "かじとり",
    "def": "helmsman, steering",
    "ch": 2
   },
   {
    "w": "物見",
    "read": "ものみ",
    "def": "lookout, scout",
    "ch": 2
   },
   {
    "w": "万歳",
    "read": "ばんざい",
    "def": "hurrah!",
    "ch": 2
   },
   {
    "w": "見はり",
    "read": "みはり",
    "def": "watch, guard",
    "ch": 2
   },
   {
    "w": "岩",
    "read": "いわ",
    "def": "rock",
    "ch": 2
   },
   {
    "w": "進む",
    "read": "すすむ",
    "def": "to advance, proceed",
    "ch": 2
   },
   {
    "w": "逃げる",
    "read": "にげる",
    "def": "to flee, run away",
    "ch": 3
   },
   {
    "w": "押さえる",
    "read": "おさえる",
    "def": "to hold down, restrain",
    "ch": 3
   },
   {
    "w": "降参する",
    "read": "こうさんする",
    "def": "to surrender",
    "ch": 3
   },
   {
    "w": "宝物",
    "read": "たからもの",
    "def": "treasure",
    "ch": 3
   },
   {
    "w": "喜ぶ",
    "read": "よろこぶ",
    "def": "to rejoice, be delighted",
    "ch": 3
   },
   {
    "w": "約束",
    "read": "やくそく",
    "def": "promise",
    "ch": 3
   },
   {
    "w": "積む",
    "read": "つむ",
    "def": "to load (cargo)",
    "ch": 3
   },
   {
    "w": "組みふせる",
    "read": "くみふせる",
    "def": "to wrestle down, pin down",
    "ch": 3
   }
  ],
  "ideas": [
   {
    "q": "Where did the old woman find the peach?",
    "ch": 0
   },
   {
    "q": "What happened when the old man tried to look closely at the peach?",
    "ch": 0
   },
   {
    "q": "Why do you think the old couple believed the baby was a gift from the gods?",
    "ch": 0
   },
   {
    "q": "How old was Momotarō when he decided to leave home?",
    "ch": 1
   },
   {
    "q": "What did Momotarō ask his grandfather for before leaving?",
    "ch": 1
   },
   {
    "q": "What special food did the grandparents make him for the journey — and why might it matter later in the story?",
    "ch": 1
   },
   {
    "q": "In what order did Momotarō meet the dog, the monkey and the pheasant?",
    "ch": 2
   },
   {
    "q": "What did each animal ask for before agreeing to join him?",
    "ch": 2
   },
   {
    "q": "What job did each animal take on the boat?",
    "ch": 2
   },
   {
    "q": "What job did each of the three animal companions do during the attack on the castle?",
    "ch": 3
   },
   {
    "q": "What did the ogre chief offer in exchange for his life?",
    "ch": 3
   },
   {
    "q": "How did the grandparents react when Momotarō came home?",
    "ch": 3
   }
  ]
 },
 {
  "id": "urashima-taro",
  "authentic": true,
  "band": "authentic",
  "moves": {},
  "quick": [],
  "evidence": [],
  "title": "浦島太郎",
  "en": "Urashima Tarō",
  "author": "楠山正雄 (d. 1950-11-26)",
  "translator": "",
  "died": "1950-11-26",
  "card": "https://www.aozora.gr.jp/cards/000329/card3390.html",
  "orthography": "新字新仮名",
  "beyond": [
   "mostly plain/です・ます mixed narration; no classical grammar",
   "some archaic vocabulary (こうら, べっとう-style era words) glossed in the vocab lists"
  ],
  "attribution": [
   "底本：「むかし むかし あるところに」童話屋",
   "1996（平成8）年6月24日初版発行",
   "1996（平成8）年7月10日第2刷発行",
   "底本の親本：「日本童話宝玉集（上中下版）」童話春秋社",
   "1948（昭和23）〜1949（昭和24）年発行",
   "入力：鈴木厚司",
   "校正：林　幸雄",
   "2001年12月19日公開",
   "2008年10月10日修正",
   "青空文庫作成ファイル：",
   "このファイルは、インターネットの図書館、青空文庫（http://www.aozora.gr.jp/）で作られました。入力、校正、制作にあたったのは、ボランティアの皆さんです。"
  ],
  "chapters": [
   {
    "t": "第一章",
    "en": "The Turtle's Thanks",
    "from": 0,
    "to": 57
   },
   {
    "t": "第二章",
    "en": "The Palace Under the Sea",
    "from": 58,
    "to": 91
   },
   {
    "t": "第三章",
    "en": "Homesick",
    "from": 92,
    "to": 123
   },
   {
    "t": "第四章",
    "en": "Three Hundred Years",
    "from": 124,
    "to": 177
   }
  ],
  "sentences": [
   "むかし、むかし、<ruby>丹後<rt>たんご</rt></ruby>の国<ruby>水<rt>みず</rt></ruby>の<ruby>江<rt>え</rt></ruby>の<ruby>浦<rt>うら</rt></ruby>に、浦島太郎というりょうしがありました。",
   "浦島太郎は、毎日つりざおをかついでは海へ出かけて、たいや、かつおなどのおさかなをつって、おとうさんおかあさんをやしなっていました。",
   "ある日、浦島はいつものとおり海へ出て、一日おさかなをつって、帰ってきました。",
   "<ruby>途中<rt>とちゅう</rt></ruby>、子どもが五、六人<ruby>往来<rt>おうらい</rt></ruby>にあつまって、がやがやいっていました。",
   "<ruby>何<rt>なに</rt></ruby>かとおもって浦島がのぞいてみると、小さいかめの子を一ぴきつかまえて、<ruby>棒<rt>ぼう</rt></ruby>でつついたり、石でたたいたり、さんざんにいじめているのです。",
   "浦島は見かねて、",
   "「まあ、そんなかわいそうなことをするものではない。",
   "いい子だから」",
   "と、とめましたが、子どもたちはきき入れようともしないで、",
   "「なんだい。",
   "なんだい、かまうもんかい」",
   "といいながら、またかめの子を、あおむけにひっくりかえして、足でけったり、<ruby>砂<rt>すな</rt></ruby>のなかにうずめたりしました。",
   "浦島はますますかわいそうにおもって、",
   "「じゃあ、おじさんがおあしをあげるから、そのかめの子を売っておくれ」",
   "といいますと、こどもたちは、",
   "「うんうん、おあしをくれるならやってもいい」",
   "といって、手を出しました。",
   "そこで浦島はおあしをやってかめの子をもらいうけました。",
   "子どもたちは、",
   "「おじさん、ありがとう。",
   "また買っておくれよ」",
   "と、わいわいいいながら、行ってしまいました。",
   "そのあとで浦島は、こうらからそっと出したかめの<ruby>首<rt>くび</rt></ruby>をやさしくなでてやって、",
   "「やれやれ、あぶないところだった。",
   "さあもうお帰りお帰り」",
   "といって、わざわざ、かめを海ばたまで持って行ってはなしてやりました。",
   "かめはさもうれしそうに、首や手足をうごかして、やがて、ぶくぶくあわをたてながら、水のなかにふかくしずんで行ってしまいました。",
   "それから二、三日たって、浦島はまた舟にのって海へつりに出かけました。",
   "遠い<ruby>沖<rt>おき</rt></ruby>のほうまでもこぎ出して、<ruby>一生<rt>いっしょう</rt></ruby>けんめいおさかなをつっていますと、ふとうしろのほうで",
   "「浦島さん、浦島さん」",
   "とよぶ声がしました。",
   "おやとおもってふりかえってみますと、だれも人のかげは見えません。",
   "その<ruby>代<rt>かわ</rt></ruby>り、いつのまにか、一ぴきのかめが、舟のそばにきていました。",
   "浦島がふしぎそうな顔をしていると、",
   "「わたくしは、先日<ruby>助<rt>たす</rt></ruby>けていただいたかめでございます。",
   "きょうはちょっとそのお<ruby>礼<rt>れい</rt></ruby>にまいりました」",
   "かめがこういったので、浦島はびっくりしました。",
   "「まあ、そうかい。",
   "わざわざ礼なんぞいいにくるにはおよばないのに」",
   "「でも、ほんとうにありがとうございました。",
   "ときに、浦島さん、あなたはりゅう<ruby>宮<rt>ぐう</rt></ruby>をごらんになったことがありますか」",
   "「いや、話にはきいているが、まだ見たことはないよ」",
   "「ではほんのお礼のしるしに、わたくしがりゅう宮を見せて上げたいとおもいますがいかがでしょう」",
   "「へえ、それはおもしろいね。",
   "ぜひ行ってみたいが、それはなんでも海の底にあるということではないか。",
   "どうして行くつもりだね。",
   "わたしにはとてもそこまでおよいでは行けないよ」",
   "「なに、わけはございません。",
   "わたくしの<ruby>背中<rt>せなか</rt></ruby>におのりください」",
   "かめはこういって、背中を出しました。",
   "浦島は半分きみわるくおもいながら、いわれるままに、かめの背中にのりました。",
   "かめはすぐに白い<ruby>波<rt>なみ</rt></ruby>を切って、ずんずんおよいで行きました。",
   "ざあざあいう波の音がだんだん<ruby>遠<rt>とお</rt></ruby>くなって、青い青い水の底へ、ただもう<ruby>夢<rt>ゆめ</rt></ruby>のようにはこばれて行きますと、ふと、そこらがかっとあかるくなって、<ruby>白玉<rt>しらたま</rt></ruby>のようにきれいな<ruby>砂<rt>すな</rt></ruby>の<ruby>道<rt>みち</rt></ruby>がつづいて、むこうにりっぱな門が見えました。",
   "その<ruby>奥<rt>おく</rt></ruby>にきらきら光って、目のくらむような金銀のいらかが、たかくそびえていました。",
   "「さあ、りゅう<ruby>宮<rt>ぐう</rt></ruby>へまいりました」",
   "かめはこういって、浦島を<ruby>背中<rt>せなか</rt></ruby>からおろして、",
   "「しばらくお待ちください」",
   "といったまま、門のなかへはいって行きました。",
   "まもなく、かめはまた出てきて、",
   "「さあ、こちらへ」",
   "と、浦島を<ruby>御殿<rt>ごてん</rt></ruby>のなかへ<ruby>案内<rt>あんない</rt></ruby>しました。",
   "たいや、ひらめやかれいや、いろいろのおさかなが、ものめずらしそうな目で見ているなかをとおって、はいって行きますと、<ruby>乙姫<rt>おとひめ</rt></ruby>さまがおおぜいの<ruby>腰元<rt>こしもと</rt></ruby>をつれて、お<ruby>迎<rt>むか</rt></ruby>えに出てきました。",
   "やがて<ruby>乙姫<rt>おとひめ</rt></ruby>さまについて、浦島はずんずん<ruby>奥<rt>おく</rt></ruby>へとおって行きました。",
   "めのうの<ruby>天井<rt>てんじょう</rt></ruby>にさんごの柱、<ruby>廊下<rt>ろうか</rt></ruby>にはるりがしきつめてありました。",
   "こわごわその上をあるいて行きますと、どこからともなくいいにおいがして、たのしい<ruby>楽<rt>がく</rt></ruby>の<ruby>音<rt>ね</rt></ruby>がきこえてきました。",
   "やがて、<ruby>水晶<rt>すいしょう</rt></ruby>の<ruby>壁<rt>かべ</rt></ruby>に、いろいろの<ruby>宝石<rt>ほうせき</rt></ruby>をちりばめた<ruby>大広間<rt>おおひろま</rt></ruby>にとおりますと、",
   "「浦島さん、ようこそおいでくださいました。",
   "先日はかめのいのちをお<ruby>助<rt>たす</rt></ruby>けくださいまして、まことにありがとうございます。",
   "なんにもおもてなしはございませんが、どうぞゆっくりおあそびくださいまし」",
   "と、乙姫さまはいって、ていねいにおじぎしました。",
   "やがて、たいをかしらに、かつおだの、ふぐだの、えびだの、たこだの、大小いろいろのおさかなが、めずらしいごちそうを山とはこんできて、にぎやかなお<ruby>酒盛<rt>さかもり</rt></ruby>がはじまりました。",
   "きれいな<ruby>腰元<rt>こしもと</rt></ruby>たちは、歌をうたったり<ruby>踊<rt>おど</rt></ruby>りをおどったりしました。",
   "浦島はただもう<ruby>夢<rt>ゆめ</rt></ruby>のなかで夢を見ているようでした。",
   "ごちそうがすむと、浦島はまた乙姫さまの<ruby>案内<rt>あんない</rt></ruby>で、<ruby>御殿<rt>ごてん</rt></ruby>のなかをのこらず見せてもらいました。",
   "どのおへやも、どのおへやも、めずらしい宝石でかざり立ててありますからそのうつくしさは、とても口やことばではいえないくらいでした。",
   "ひととおり見てしまうと、<ruby>乙姫<rt>おとひめ</rt></ruby>さまは、",
   "「こんどは四季のけしきをお目にかけましょう」",
   "といって、まず、東の戸をおあけになりました。",
   "そこは春のけしきで、いちめん、ぼうっとかすんだなかに、さくらの花が、うつくしい絵のように咲き<ruby>乱<rt>みだ</rt></ruby>れていました。",
   "<ruby>青青<rt>あおあお</rt></ruby>としたやなぎの<ruby>枝<rt>えだ</rt></ruby>が風になびいて、そのなかで小鳥がないたり、ちょうちょうが<ruby>舞<rt>ま</rt></ruby>ったりしていました。",
   "次に、南の戸をおあけになりました。",
   "そこは夏のけしきで、<ruby>垣根<rt>かきね</rt></ruby>には白いうの花が咲いて、お庭の木の<ruby>青葉<rt>あおば</rt></ruby>のなかでは、せみやひぐらしがないていました。",
   "お池には赤と白のはすの花が咲いて、その葉の上には、<ruby>水晶<rt>すいしょう</rt></ruby>の<ruby>珠<rt>たま</rt></ruby>のように<ruby>露<rt>つゆ</rt></ruby>がたまっていました。",
   "お池のふちには、きれいなさざ<ruby>波<rt>なみ</rt></ruby>が立って、おしどりやかもがうかんでいました。",
   "次に西の戸をおあけになりました。",
   "そこは秋のけしきで<ruby>花壇<rt>かだん</rt></ruby>のなかには、黄ぎく、<ruby>白<rt>しら</rt></ruby>ぎくが咲き乱れて、ぷんといいかおりを立てました。",
   "むこうを見ると、かっともえ立つようなもみじの林の<ruby>奥<rt>おく</rt></ruby>に、白い<ruby>霧<rt>きり</rt></ruby>がたちこめていて、しかのなく声がかなしくきこえました。",
   "いちばんおしまいに、北の戸をおあけになりました。",
   "そこは冬のけしきで、野には<ruby>散<rt>ち</rt></ruby>りのこった<ruby>枯葉<rt>かれは</rt></ruby>の上に、<ruby>霜<rt>しも</rt></ruby>がきらきら光っていました。",
   "山から谷にかけて、雪がまっ白に降り<ruby>埋<rt>うず</rt></ruby>んだなかから、<ruby>柴<rt>しば</rt></ruby>をたくけむりがほそぼそとあがっていました。",
   "浦島は何を見ても、おどろきあきれて、目ばかり見はっていました。",
   "そのうちだんだんぼうっとしてきて、お酒に<ruby>酔<rt>よ</rt></ruby>った人のようになって、何もかもわすれてしまいました。",
   "毎日おもしろい、めずらしいことが、それからそれとつづいて、あまりりゅう宮がたのしいので、なんということもおもわずに、うかうかあそんでくらすうち、三年の月日がたちました。",
   "三年めの春になったとき、浦島はときどき、ひさしくわすれていたふるさとの<ruby>夢<rt>ゆめ</rt></ruby>を見るようになりました。",
   "春の日のぽかぽかあたっている<ruby>水<rt>みず</rt></ruby>の<ruby>江<rt>え</rt></ruby>の浜べで、りょうしたちがげんきよく舟うたをうたいながら、<ruby>網<rt>あみ</rt></ruby>をひいたり舟をこいだりしているところを、まざまざと夢に見るようになりました。",
   "浦島はいまさらのように、",
   "「おとうさんや、おかあさんは、いまごろどうしておいでになるだろう」",
   "と、こうおもい出すと、もう、いても立ってもいられなくなるような気がしました。",
   "なんでも早くうちへ帰りたいとばかりおもうようになりました。",
   "ですから、もうこのごろでは、歌をきいても、<ruby>踊<rt>おど</rt></ruby>りを見ても、おもしろくない顔をして、ふさぎこんでばかりいました。",
   "その<ruby>様子<rt>ようす</rt></ruby>を見ると、<ruby>乙姫<rt>おとひめ</rt></ruby>さまは<ruby>心配<rt>しんぱい</rt></ruby>して、",
   "「浦島さん、ご気分でもおわるいのですか」",
   "とおききになりました。",
   "浦島はもじもじしながら、",
   "「いいえ、そうではありません。",
   "じつはうちへ帰りたくなったものですから」",
   "といいますと、乙姫さまはきゅうに、たいそうがっかりした様子をなさいました。",
   "「まあ、それはざんねんでございますこと。",
   "でもあなたのお顔をはいけんいたしますと、この上おひきとめ申しても、むだのようにおもわれます。",
   "ではいたし<ruby>方<rt>かた</rt></ruby>ございません、行っていらっしゃいまし」",
   "こうかなしそうにいって、乙姫さまは、<ruby>奥<rt>おく</rt></ruby>からきれいな<ruby>宝石<rt>ほうせき</rt></ruby>でかざった<ruby>箱<rt>はこ</rt></ruby>を持っておいでになって、",
   "「これは<ruby>玉手箱<rt>たまてばこ</rt></ruby>といって、なかには、人間のいちばんだいじなたからがこめてございます。",
   "これをおわかれのしるしにさし上げますから、お持ちかえりくださいまし。",
   "ですが、あなたがもういちどりゅう<ruby>宮<rt>ぐう</rt></ruby>へ帰ってきたいとおぼしめすなら、どんなことがあっても、けっしてこの箱をあけてごらんになってはいけません」",
   "と、くれぐれもねんをおして、<ruby>玉手箱<rt>たまてばこ</rt></ruby>をおわたしになりました。",
   "浦島は、",
   "「ええ、ええ、けっしてあけません」",
   "といって、玉手箱をこわきにかかえたまま、りゅう<ruby>宮<rt>ぐう</rt></ruby>の門を出ますと、<ruby>乙姫<rt>おとひめ</rt></ruby>さまは、またおおぜいの<ruby>腰元<rt>こしもと</rt></ruby>をつれて、門のそとまでお見送りになりました。",
   "もうそこには、れいのかめがきて待っていました。",
   "浦島はうれしいのとかなしいのとで、<ruby>胸<rt>むね</rt></ruby>がいっぱいになっていました。",
   "そしてかめの<ruby>背中<rt>せなか</rt></ruby>にのりますと、かめはすぐ<ruby>波<rt>なみ</rt></ruby>を切って上がって行って、まもなくもとの浜べにつきました。",
   "「では浦島さん、ごきげんよろしゅう」",
   "と、かめはいって、また水のなかにもぐって行きました。",
   "浦島はしばらく、かめの<ruby>行<rt>ゆ</rt></ruby>くえを見送っていました。",
   "浦島は海ばたに立ったまま、しばらくそこらを見まわしました。",
   "春の日がぽかぽかあたって、いちめんにかすんだ海の上に、どこからともなく、にぎやかな舟うたがきこえました。",
   "それは<ruby>夢<rt>ゆめ</rt></ruby>のなかで見たふるさとの浜べの<ruby>景色<rt>けしき</rt></ruby>とちっともちがったところはありませんでした。",
   "けれどよく見ると、そこらの<ruby>様子<rt>ようす</rt></ruby>がなんとなくかわっていて、あう人もあう人も、いっこうに見知らない顔ばかりで、むこうでもみょうな顔をして、じろじろ見ながら、ことばもかけずにすまして行ってしまいます。",
   "「おかしなこともあるものだ。",
   "たった三年のあいだに、みんなどこかへ行ってしまうはずはない。",
   "まあ、なんでも早くうちへ行ってみよう」",
   "こうひとりごとをいいながら、浦島はじぶんの家の<ruby>方角<rt>ほうがく</rt></ruby>へあるき出しました。",
   "ところが、そことおもうあたりには草やあしがぼうぼうとしげって、家なぞはかげもかたちもありません。",
   "むかし家の立っていたらしいあとさえものこってはいませんでした。",
   "いったい、おとうさんやおかあさんはどうなったのでしょうか。",
   "浦島は、",
   "「ふしぎだ。",
   "ふしぎだ」",
   "とくり返しながら、きつねにつままれたような、きょとんとした顔をしていました。",
   "するとそこへ、よぼよぼのおばあさんがひとり、つえにすがってやってきました。",
   "浦島はさっそく、",
   "「もしもし、おばあさん、浦島太郎のうちはどこでしょう」",
   "と、声をかけますと、おばあさんはけげんそうに、しょぼしょぼした目で、浦島の顔をながめながら、",
   "「へえ、浦島太郎。",
   "そんな人はきいたことがありませんよ」",
   "といいました。",
   "浦島はやっきとなって、",
   "「そんなはずはありません。",
   "たしかにこのへんに住んでいたのです」",
   "といいました。",
   "そういわれて、おばあさんは、",
   "「はてね」と、<ruby>首<rt>くび</rt></ruby>をかしげながら、つえでせいのびしてしばらくかんがえこんでいましたが、やがてぽんとひざをたたいて、",
   "「ああ、そうそう、浦島太郎さんというと、あれはもう三百年も前の人ですよ。",
   "なんでも、わたしが子どものじぶんきいた話に、むかし、むかし、この<ruby>水<rt>みず</rt></ruby>の<ruby>江<rt>え</rt></ruby>の浜に、浦島太郎という人があって、ある日、舟にのってつりに出たまま、帰ってこなくなりました。",
   "たぶんりゅう<ruby>宮<rt>ぐう</rt></ruby>へでも行ったのだろうということです。",
   "なにしろ<ruby>大昔<rt>おおむかし</rt></ruby>の話だからね」",
   "こういって、また<ruby>腰<rt>こし</rt></ruby>をかがめて、よぼよぼあるいて行ってしまいました。",
   "浦島はびっくりしてしまいました。",
   "「はて、三百年、おかしなこともあるものだ。",
   "たった三年りゅう宮にいたつもりなのに、それが三百年とは。",
   "するとりゅう<ruby>宮<rt>ぐう</rt></ruby>の三年は、人間の三百年にあたるのかしらん。",
   "それでは家もなくなるはずだし、おとうさんやおかあさんがいらっしゃらないのもふしぎはない」",
   "こうおもうと、浦島はきゅうにかなしくなって、さびしくなって、目の前がくらくなりました。",
   "いまさらりゅう宮がこいしくてたまらなくなりました。",
   "しおしおとまた浜べへ出てみましたが、海の水はまんまんとたたえていて、どこがはてともしれません。",
   "もうかめも出てきませんから、どうしてりゅう宮へわたろう手だてもありませんでした。",
   "そのとき、浦島はふと、かかえていた<ruby>玉手箱<rt>たまてばこ</rt></ruby>に気がつきました。",
   "「そうだ。",
   "この<ruby>箱<rt>はこ</rt></ruby>をあけてみたらば、わかるかもしれない」",
   "こうおもうとうれしくなって、浦島は、うっかり<ruby>乙姫<rt>おとひめ</rt></ruby>さまにいわれたことはわすれて、箱のふたをとりました。",
   "するとむらさき色の雲が、なかからむくむく立ちのぼって、それが顔にかかったかとおもうと、すうっと消えて行って箱のなかにはなんにものこっていませんでした。",
   "その<ruby>代<rt>かわ</rt></ruby>り、いつのまにか顔じゅうしわになって、手も足もちぢかまって、きれいなみぎわの水にうつった<ruby>影<rt>かげ</rt></ruby>を見ると、<ruby>髪<rt>かみ</rt></ruby>もひげも、まっしろな、かわいいおじいさんになっていました。",
   "浦島はからになった<ruby>箱<rt>はこ</rt></ruby>のなかをのぞいて、",
   "「なるほど、<ruby>乙姫<rt>おとひめ</rt></ruby>さまが、人間のいちばんだいじなたからを入れておくとおっしゃったあれは、人間の<ruby>寿命<rt>じゅみょう</rt></ruby>だったのだな」",
   "と、ざんねんそうにつぶやきました。",
   "春の海はどこまでも<ruby>遠<rt>とお</rt></ruby>くかすんでいました。",
   "どこからかいい声で舟うたをうたうのが、またきこえてきました。",
   "浦島は、ぼんやりとむかしのことをおもい出していました。"
  ],
  "notebook": [
   {
    "w": "りょうし",
    "read": "りょうし",
    "def": "fisherman",
    "ch": 0
   },
   {
    "w": "いじめる",
    "read": "いじめる",
    "def": "to bully, torment",
    "ch": 0
   },
   {
    "w": "かめ",
    "read": "かめ",
    "def": "turtle",
    "ch": 0
   },
   {
    "w": "助ける",
    "read": "たすける",
    "def": "to save, help",
    "ch": 0
   },
   {
    "w": "お礼",
    "read": "おれい",
    "def": "thanks, gratitude",
    "ch": 0
   },
   {
    "w": "りゅう宮",
    "read": "りゅうぐう",
    "def": "Dragon Palace",
    "ch": 0
   },
   {
    "w": "背中",
    "read": "せなか",
    "def": "back (of the body)",
    "ch": 0
   },
   {
    "w": "門",
    "read": "もん",
    "def": "gate",
    "ch": 0
   },
   {
    "w": "乙姫",
    "read": "おとひめ",
    "def": "Princess Oto (the palace princess)",
    "ch": 1
   },
   {
    "w": "案内する",
    "read": "あんないする",
    "def": "to guide, show around",
    "ch": 1
   },
   {
    "w": "御殿",
    "read": "ごてん",
    "def": "palace",
    "ch": 1
   },
   {
    "w": "ごちそう",
    "read": "ごちそう",
    "def": "a feast, a treat",
    "ch": 1
   },
   {
    "w": "四季",
    "read": "しき",
    "def": "the four seasons",
    "ch": 1
   },
   {
    "w": "咲く",
    "read": "さく",
    "def": "to bloom",
    "ch": 1
   },
   {
    "w": "けしき",
    "read": "けしき",
    "def": "scenery, view",
    "ch": 1
   },
   {
    "w": "夢",
    "read": "ゆめ",
    "def": "dream",
    "ch": 1
   },
   {
    "w": "ふるさと",
    "read": "ふるさと",
    "def": "hometown",
    "ch": 2
   },
   {
    "w": "心配する",
    "read": "しんぱいする",
    "def": "to worry",
    "ch": 2
   },
   {
    "w": "がっかりする",
    "read": "がっかりする",
    "def": "to be disappointed",
    "ch": 2
   },
   {
    "w": "玉手箱",
    "read": "たまてばこ",
    "def": "the treasure/keepsake box",
    "ch": 2
   },
   {
    "w": "わかれ",
    "read": "わかれ",
    "def": "parting, farewell",
    "ch": 2
   },
   {
    "w": "あける",
    "read": "あける",
    "def": "to open",
    "ch": 2
   },
   {
    "w": "けっして〜ない",
    "read": "けっして〜ない",
    "def": "never (do something)",
    "ch": 2
   },
   {
    "w": "見送り",
    "read": "みおくり",
    "def": "seeing someone off",
    "ch": 2
   },
   {
    "w": "見知らない",
    "read": "みしらない",
    "def": "unfamiliar, unknown",
    "ch": 3
   },
   {
    "w": "ふしぎ",
    "read": "ふしぎ",
    "def": "strange, mysterious",
    "ch": 3
   },
   {
    "w": "つえ",
    "read": "つえ",
    "def": "walking stick, cane",
    "ch": 3
   },
   {
    "w": "三百年",
    "read": "さんびゃくねん",
    "def": "three hundred years",
    "ch": 3
   },
   {
    "w": "寿命",
    "read": "じゅみょう",
    "def": "lifespan",
    "ch": 3
   },
   {
    "w": "開ける",
    "read": "あける",
    "def": "to open",
    "ch": 3
   },
   {
    "w": "しわ",
    "read": "しわ",
    "def": "wrinkle",
    "ch": 3
   },
   {
    "w": "まっしろ",
    "read": "まっしろ",
    "def": "pure white",
    "ch": 3
   }
  ],
  "ideas": [
   {
    "q": "What were the children doing to the turtle when Urashima found them?",
    "ch": 0
   },
   {
    "q": "How did Urashima save the turtle?",
    "ch": 0
   },
   {
    "q": "Why did the turtle come back to find Urashima later?",
    "ch": 0
   },
   {
    "q": "Who welcomed Urashima at the Dragon Palace?",
    "ch": 1
   },
   {
    "q": "What did Otohime show Urashima after the feast?",
    "ch": 1
   },
   {
    "q": "How does the story describe the way Urashima felt the whole time he was there?",
    "ch": 1
   },
   {
    "q": "How long had Urashima actually been at the Dragon Palace when he decided to go home?",
    "ch": 2
   },
   {
    "q": "What rule did Otohime give him about the tamatebako (treasure box)?",
    "ch": 2
   },
   {
    "q": "How did Otohime seem to feel about him leaving?",
    "ch": 2
   },
   {
    "q": "What did the old woman tell Urashima had happened to \"Urashima Tarō\" 300 years ago?",
    "ch": 3
   },
   {
    "q": "What happened to Urashima's body the moment he opened the box?",
    "ch": 3
   },
   {
    "q": "What do you think was really kept inside the tamatebako?",
    "ch": 3
   }
  ]
 },
 {
  "id": "cinderella-the-glass-slipper",
  "authentic": true,
  "band": "authentic",
  "moves": {},
  "quick": [],
  "evidence": [],
  "title": "灰だらけ姫（ガラスの上ぐつ）",
  "en": "Cinderella (The Glass Slipper)",
  "author": "ペロー（Charles Perrault, 1628–1703） (d. 1703)",
  "translator": "楠山正雄 (d. 1950-11-26)",
  "died": "1703",
  "card": "https://www.aozora.gr.jp/cards/001134/card43120.html",
  "orthography": "新字新仮名",
  "beyond": [
   "polite narrative past tense throughout; no classical grammar",
   "some old-fashioned katakana loanwords (ビロード=velvet, など) glossed in vocab"
  ],
  "attribution": [
   "底本：「世界おとぎ文庫（イギリス・フランス童話篇）妖女のおくりもの」小峰書店",
   "1950（昭和25）年5月1日発行",
   "※「旧字、旧仮名で書かれた作品を、現代表記にあらためる際の作業指針」に基づいて、底本の表記をあらためました。",
   "※底本は、表題の「灰かぶり姫」に「サンドリヨン」とルビをふっています。",
   "入力：大久保ゆう",
   "校正：秋鹿",
   "2006年1月21日作成",
   "青空文庫作成ファイル：",
   "このファイルは、インターネットの図書館、青空文庫（http://www.aozora.gr.jp/）で作られました。入力、校正、制作にあたったのは、ボランティアの皆さんです。"
  ],
  "chapters": [
   {
    "t": "第一章",
    "en": "The Ash-Covered Girl",
    "from": 0,
    "to": 14
   },
   {
    "t": "第二章",
    "en": "The Fairy Godmother",
    "from": 15,
    "to": 95
   },
   {
    "t": "第三章",
    "en": "The Ball",
    "from": 96,
    "to": 116
   },
   {
    "t": "第四章",
    "en": "Home Before Midnight",
    "from": 117,
    "to": 144
   },
   {
    "t": "第五章",
    "en": "The Lost Slipper",
    "from": 145,
    "to": 169
   },
   {
    "t": "第六章",
    "en": "The Fitting",
    "from": 170,
    "to": 193
   }
  ],
  "sentences": [
   "むかしむかし、あるところに、なに不自由なく、くらしている<ruby>紳士<rt>しんし</rt></ruby>がありました。",
   "ところが、その二どめにもらったおくさんというのは、それはそれは、ふたりとない、こうまんでわがままな、いばりやでした。",
   "まえのご主人とのなかに、ふたりもこどもがあって、つれ子をしておよめに来たのですが、そのむすめたちというのが、やはり、なにから、なにまでおかあさんにそっくりな、いけないわがままむすめでした。",
   "さて、この<ruby>紳士<rt>しんし</rt></ruby>には、まえのおくさんから生まれた、もうひとりの若いむすめがありましたが、それは気だてなら、心がけなら、とてもいいひとだった<ruby>亡<rt>な</rt></ruby>くなった母親そっくりで、このうえないすなおな、やさしい子でした。",
   "<ruby>結婚<rt>けっこん</rt></ruby>の<ruby>儀式<rt>ぎしき</rt></ruby>がすむとまもなく、こんどのおかあさんは、さっそくいじわるの<ruby>本性<rt>ほんしょう</rt></ruby>をさらけ出しました。",
   "このおかあさんにとっては、腹ちがいのむすめが、心がけがよくて、そのため、よけいじぶんの生んだこどもたちのあらの見えるのが、なによりもがまんできないことでした。",
   "そこで、ままむすめを<ruby>台所<rt>だいどころ</rt></ruby>にさげて、女中のするしごとに追いつかいました。",
   "お皿を洗ったり、おぜんごしらえをしたり、おくさまのおへやのそうじから、おじょうさまたちのお居間のそうじまで、させられました。",
   "そうして、じぶんは、うちのてっぺんの、屋根うらの、くもの巣だらけなすみで、わらのねどこに、犬のようにまるくなって眠らなければなりませんでした。",
   "そのくせ、ふたりのきょうだいたちは、うつくしいモザイクでゆかをしきつめた、あたたかい、きれいなおへやの中で、りっぱなかざりのついたねだいに眠って、そこには、頭から足のつまさきまでうつる、大きなすがたみもありました。",
   "かわいそうなむすめは、なにもかもじっとこらえていました。",
   "父親は、すっかり母親にまるめられていて、いっしょになって、こごとをいうばかりでしたから、むすめはなにも話しませんでした。",
   "それで、いいつかったしごとをすませると、いつも、かまどの前にかがんで、<ruby>消炭<rt>けしずみ</rt></ruby>や灰の中にうずくまっていましたから、ままむすめの姉と妹は、からかい半分、サンドリヨン（シンデレラ）というあだ名をつけました。",
   "これは灰のかたまりとか、消炭とかいうことで、つまり、それは、「灰だらけ娘」とでもいうことになりましょう。",
   "それにしても、サンドリヨンは、どんなに、きたない身なりはしていても、美しく着かざったふたりのきょうだいたちにくらべては、百そうばいもきれいでしたし、まして心のうつくしさは、くらべものになりませんでした。",
   "さてあるとき、その国の王様の王子が、さかんなぶとう会をもよおして、おおぜい身分のいい人たちを、ダンスにおまねきになったことがありました。",
   "サンドリヨンのふたりのきょうだいも、はばのきくおとうさんのむすめたちでしたから、やはり、ぶとう会におまねきをうけていました。",
   "ふたりは、おまねきをうけてから、それはおかしいように、のぼせあがって、<ruby>上着<rt>うわぎ</rt></ruby>よ、がいとうよ、ずきんよと、まい日えりこのみに、うき身をやつしておりました。",
   "おかげで、サンドリヨンには、新しいやっかいしごとがひとつふえました。",
   "なぜというに、きょうだいたちの着物に火のしをかけたり、<ruby>袖口<rt>そでぐち</rt></ruby>にかざりぬいしたりするのは、みんなサンドリヨンのしごとだったからです。",
   "ふたりは朝から晩まで、おめかしの話ばかりしていました。",
   "「わたしは、イギリスかざりのついた、赤いビロードの着物にしようとおもうのよ。」",
   "と、姉はいいました。",
   "「じゃあ、わたしは、いつものスカートにしておくわ。",
   "けれど、そのかわり、金の花もようのマントを着るわ。",
   "そうして、ダイヤモンドの<ruby>帯<rt>おび</rt></ruby>をするわ。",
   "あれは<ruby>世間<rt>せけん</rt></ruby>にめったにない品物なんだもの。」",
   "ふたりは、そのじぶん、<ruby>上手<rt>じょうず</rt></ruby>でひょうばんの<ruby>美容師<rt>びようし</rt></ruby>をよんで、頭のかざりから足のくつ先まで、一<ruby>分<rt>ぶ</rt></ruby>のすきもなしに、すっかり、<ruby>流行<rt>りゅうこう</rt></ruby>のしたくをととのえさせました。",
   "サンドリヨンも、やはりそういうことのそうだんに、いちいち使われていました。",
   "なにしろ、このむすめは、もののよしあしのよく分かる子でしたから、ふたりのために、いっしょうけんめい、くふうしてやって、おまけに、おけしょうまで手つだってやりました。",
   "サンドリヨンに<ruby>髪<rt>かみ</rt></ruby>をあげてもらいながら、ふたりは、",
   "「サンドリヨン、おまえさんも、ぶとう会に行きたいとはおもわないかい。」",
   "といいました。",
   "「まあ、おねえさまたちは、わたしをからかっていらっしゃるのね。",
   "わたしのようなものが、どうして行かれるものですか。」",
   "「そうだとも、灰だらけ娘のくせに、ぶとう会なんぞに出かけて行ったら、みんなさぞ笑うだろうよ。」",
   "と、ふたりはいいました。",
   "こんなことをいわれて、これがサンドリヨンでなかったら、ふたりの<ruby>髪<rt>かみ</rt></ruby>をひんまげてもやりたいとおもうところでしょうが、このむすめは、それは人のいい子でしたから、あくまでたのまれたとおり、りっぱにおけしょうをしあげてやりました。",
   "ふたりのきょうだいたちは、もう、むやみとうれしくて、ふつかのあいだ、ろくろく物もたべないくらいでした。",
   "そのうえ、でぶでぶしたからだを、ほっそりしなやかに見せようとおもって、一ダースもレースをからだにまきつけました。",
   "そうして、ひまさえあれば、すがたみの前に立っていました。",
   "やがて、待ちに待った、たのしい日になりました。",
   "ふたりは庭におりて、出かけるしたくをしていました。",
   "サンドリヨンは、そのあとから、じっと見送れるだけ見送っていました。",
   "いよいよすがたが見えなくなってしまうと、いきなりそこに泣きふしてしまいました。",
   "そのとき、ふと、サンドリヨンの<ruby>洗礼式<rt>せんれいしき</rt></ruby>に立ち合った、名づけ親の<ruby>教母<rt>きょうぼ</rt></ruby>が出て来て、むすめが泣きふしているのを見ると、どうしたのだといって、たずねました。",
   "「わたし、行きたいのです。",
   "――行きたいのです。",
   "――」こういいかけて、あとは涙で声がつまって、口がきけなくなりました。",
   "このサンドリヨンの教母というのは、やはり<ruby>妖女<rt>ようじょ</rt></ruby>でした。",
   "それで、",
   "「あなたは、ぶとう会に行きたいのでしょう。",
   "そうじゃないの。」",
   "と聞きました。",
   "「ええ。」",
   "と、サンドリヨンはさけんで、大きなため息をひとつしました。",
   "「よしよし、いい子だからね、あなたも行かれるように、わたしがしてあげるから。」",
   "と、妖女はいいました。",
   "そうして、サンドリヨンの手を引いて、そのへやへつれて行きました。",
   "「<ruby>裏<rt>うら</rt></ruby>の畠へ行って、かぼちゃをひとつ、もぎとっておいで。」",
   "サンドリヨンは、さっそく行って、なかでもいちばんいいかぼちゃをよって、妖女のところへ持ってかえりました。",
   "けれども、このかぼちゃで、どうして、ぶとう会へ行けるのか、さっぱり考えがつきませんでした。",
   "かぼちゃを受けとると、妖女は、そのしんをのこらずくり抜いて、皮だけのこしました。",
   "それから<ruby>妖女<rt>ようじょ</rt></ruby>は、手に持ったつえで、こつ、こつ、こつと、三どたたくと、かぼちゃは、みるみる、金ぬりの、りっぱな馬車にかわりました。",
   "妖女は、それから、<ruby>台所<rt>だいどころ</rt></ruby>のねずみおとしをのぞきに行きました。",
   "するとそこに、はつかねずみが六ぴき、まだぴんぴん生きていました。",
   "妖女は、サンドリヨンにいいつけて、ねずみおとしの戸をすこしあげさせますと、ねずみたちが、うれしがって、ちょろ、ちょろ、かけ出すところを、つえでさわりますと、ねずみはすぐと、りっぱな馬にかわって、ねずみ色の馬車馬が六とう、そこにできました。",
   "けれども、まだ<ruby>御者<rt>ぎょしゃ</rt></ruby>がありませんでした。",
   "「わたし行って、見て来ましょう。",
   "大ねずみが、まだ一ぴきかかっているかもしれませんから。",
   "それを御者にしてやりましょう。」",
   "「それがいいわ。",
   "行ってごらん。」",
   "と、妖女はいいました。",
   "サンドリヨンは行って、ねずみおとしを持って来ましたが、そのなかに、三びき、大ねずみがいました。",
   "妖女は三びきのうちで、いちばんひげのりっぱな大ねずみをより出して、つえでさわって、ふとった、元気のいい御者にかえました。",
   "それはめったに見られない、ぴんとした、りっぱな口ひげをはやしていました。",
   "それがすむと、<ruby>妖女<rt>ようじょ</rt></ruby>は、サンドリヨンにむかって、",
   "「もういちど、<ruby>裏<rt>うら</rt></ruby>のお庭へ行って、じょろのうしろにかくれているとかげを六ぴき、見つけていらっしゃい。」",
   "といいました。",
   "サンドリヨンは、いいつけられたとおり、とかげをとってかえりますと、妖女はすぐ、それを六人のべっとうにかえてしまいました。",
   "それは、金や銀のぬいはくのある、ぴかぴかの<ruby>制服<rt>せいふく</rt></ruby>を着て、馬車のうしろの<ruby>台<rt>だい</rt></ruby>にのりました。",
   "そうして、そこに、ぺったりへばりついたなり、押しっくらしていました。",
   "そのとき、妖女は、サンドリヨンにいいました。",
   "「ほら、これでダンスに行くお供ぞろいができたでしょう。",
   "どう、気に入って。」",
   "「ええ、ええ、気に入りましたとも。」",
   "と、サンドリヨンは、うれしそうにさけびました。",
   "「けれどわたし、こんなきたないぼろを、着て行かなければならないでしょうか。」",
   "妖女はそこで、ほんのわずか、つえの先で、サンドリヨンのからだにさわったとおもうと、みるみる、つぎはぎだらけの着物は、<ruby>宝石<rt>ほうせき</rt></ruby>をちりばめた金と銀の着物にかわってしまいました。",
   "それがすむと、妖女はサンドリヨンに、それはそれは美しいリスの皮の<ruby>上<rt>うわ</rt></ruby>ぐつ（ガラスの上ぐつだともいいます。）",
   "を、一そくくれました。",
   "こうして、のこらずしたくができあがって、いよいよサンドリヨンが馬車にのろうとしたとき、<ruby>妖女<rt>ようじょ</rt></ruby>はあらためて、サンドリヨンにむかって、なにはおいても、夜なか十二時すぎまで、ぶとう会にいてはならないと、きびしくいいわたしました。",
   "十二時から一分でもおくれると、馬車はまたかぼちゃになるし、馬は小ねずみになるし、<ruby>御者<rt>ぎょしゃ</rt></ruby>は大ねずみになるし、べっとうはとかげになるし、着ている着物も、もとのとおりのぼろになるのだから、といってきかせました。",
   "サンドリヨンは、妖女に、けっして夜なかすぎまで、ぶとう会にはいませんという、かたいやくそくをしました。",
   "そうして、もうはち切れそうなうれしさを、おさえることができないようなふうで、馬車にのりました。",
   "さて、王子は、その晩、たれも知らない、どこぞのりっぱな王女が、いましがた馬車にのって、ぶとう会についたという知らせを聞いて、わざわざ迎えに出て来ました。",
   "王子は、王女が馬車からおりると、その手をとって広間の、みんなおおぜい居る中へ<ruby>案内<rt>あんない</rt></ruby>して来ました。",
   "すると、広間の中はたちまち、しんと静まりかえって、みんなダンスをやめました。",
   "バイオリンの<ruby>音<rt>ね</rt></ruby>もしなくなりました。",
   "それは、このめずらしいお客さまの美しさに、たれもかれも気をとられて、ぼんやりしてしまったからでした。",
   "そのなかで、ただかすかに、こそこそ、ささやく声がして、",
   "「ほう、きれいだなあ。",
   "ほう、きれいだなあ。」",
   "とばかり、いっていました。",
   "王様も、もうお年はとっておいででしたけれど、そのときは、おもわずサンドリヨンの顔を、じっとながめずにはいられませんでした。",
   "そうして、そっとお妃の耳もとにささやいて、",
   "「こんなきれいな、かわいらしいむすめを見るのは、久しぶりだ。」",
   "と、いっておいでになりました。",
   "<ruby>貴婦人<rt>きふじん</rt></ruby>たちは、貴婦人たちで、みんなじろじろと、サンドリヨンの着物から、頭のかざりものをしらべてみて、まあ、まあ、あれだけのりっぱな<ruby>材料<rt>ざいりょう</rt></ruby>と、それをこしらえるりっぱな<ruby>職人<rt>しょくにん</rt></ruby>とさえあれば、あしたにもさっそく、この<ruby>型<rt>かた</rt></ruby>で、じぶんもこしらえさせてみよう、と考えていました。",
   "王子は、サンドリヨンを、そのなかでいちばん<ruby>名誉<rt>めいよ</rt></ruby>の<ruby>上席<rt>じょうせき</rt></ruby>へ<ruby>案内<rt>あんない</rt></ruby>して、それからまた、つれ出して、いっしょにダンスをはじめました。",
   "サンドリヨンは、それはそれは、しとやかにおどったので、みんなは、いよいよびっくりしてしまいました。",
   "さて、けっこうなごちそうが、まもなく出ましたが、若い王子は、サンドリヨンの顔ばかりながめていて、ひとつものどにはとおりませんでした。",
   "サンドリヨンはやがて、じぶんのきょうだいたちのいるところへ出かけて行って、そのそばに腰をかけて、王子からもらったオレンジや、レモンを分けてやったりして、それは、いろいろやさしいそぶりをみせました。",
   "けれど、ふたりは、それがたれだか分からなかったものですから、ただもうびっくりして、目ばかりくるくるさせていました。",
   "サンドリヨンは、こうしてきょうだいたちのごきげんをとっているうちに、時計が十二時十五分前を打ちました。",
   "するといきなり、サンドリヨンは、ほかのお客たちに、ていねいにあいさつをして、ふいと出て行ってしまいました。",
   "さて、うちへかえると、サンドリヨンは、そこに待っていた<ruby>妖女<rt>ようじょ</rt></ruby>にあって、たくさんお礼をいったのち、あしたもまた、ぜひぶとう会へやってくださいといってたのみました。",
   "それは、王子の<ruby>熱心<rt>ねっしん</rt></ruby>なおのぞみであったからです。",
   "こうして、サンドリヨンが、ぶとう会であったことを、妖女にせっせと話をしていますと、やがて、ふたりのきょうだいがかえって来て、こつ、こつ、戸をたたきました。",
   "サンドリヨンは、かけて行って、戸をあけてやりました。",
   "「まあ、ずいぶん長く行っていらしったのね。」",
   "と、サンドリヨンはさけんで、あくびをして、目をこすって、のびをしました。",
   "それは、うたたねをしていて、たった今、目がさめたというようなふうでした。",
   "けれど、じつはふたりが出て行ってから、サンドリヨンは、まるっきりねたくもねられない気持だったのです。",
   "「おまえさん、ダンスに行ったら、それはたいくつなんぞしなかったろうよ。",
   "なにしろ、あそこへは、まあ、世の中に、こんなきれいな人があるかと思うほど、美しいお<ruby>姫<rt>ひめ</rt></ruby>さまが来なすったのだよ。",
   "その方が、わたしたちに、いろいろとやさしいことをおっしゃって、ごらん、こんなにレモンだの、オレンジだのをくださったのだよ。」",
   "と、きょうだいのひとりがいいました。",
   "サンドリヨンは、そんなことには、いっこうむとんじゃくなようすでした。",
   "もっとも、きょうだいたちに、そのお姫さまの名をたずねましたが、ふたりは、それは知らないといいました。",
   "そうして、王子様がそのことで、たいそうむちゅうにおなりになって、その名を、とても知りたがって、みんなにたずねておいでだったという話をしました。",
   "そう聞くと、サンドリヨンはにっこりして、",
   "「まあ、その方、どんなにお美しいでしょうね。",
   "ねえさまたち、いらしって、ほんとうによかったのね。",
   "わたし、その方見られないかしら。",
   "まあねえ、ジャボットねえさま、あなたのまい日着ていらっしゃる、黄いろい着物を、わたしにかしてくださらないこと。」",
   "といいました。",
   "「まあ、あきれた。」",
   "と、ジャボットはさけびました。",
   "「わたしの着物を、おまえさんのようなきたならしい、灰のかたまりなんかに、かしてやられるもんか。",
   "ひとをばかにしているよ。」",
   "サンドリヨンは、いずれそんな返事だろうとおもっていました。",
   "それで、そのとおりにことわられたのを、かえってありがたくおもっていました。",
   "なぜといって、きょうだいが、じょうだんをいったのを<ruby>真<rt>ま</rt></ruby>にうけて、着物をかしてくれたら、どんなになさけなくおもったでしょう。",
   "さて、そのあくる日も、ふたりのきょうだいは、ぶとう会へ出かけて行きました。",
   "サンドリヨンもやはり、こんどは、もっとりっぱに着かざって、出かけて行きました。",
   "王子は、しじゅうサンドリヨンのそばにつきっきりで、ありったけのおせじや、やさしいことばをかけていました。",
   "それがサンドリヨンには、うるさいどころではありませんでしたから、ついうかうか、<ruby>妖女<rt>ようじょ</rt></ruby>にいましめられていたことも忘れていました。",
   "それですから、まだまだ時計が十一時だと思ったのに、十二も打ったのでびっくりして、ついと立ちあがって、めじかのようにはしっこくかけ出しました。",
   "王子もすぐあとを追いかけましたが、とうとう追いつきませんでした。",
   "けれど、サンドリヨンも、あわてたまぎれに、金の<ruby>上<rt>うわ</rt></ruby>ぐつを片足落しました。",
   "それを王子は大事にしまっておきました。",
   "サンドリヨンは、うちにかえりはかえりましたが、すっかり息を切らしてしまいました。",
   "もう馬車も、べっとうもなくて、また、いつもの古着のぼろにくるまったなり、ただ片足だけはいてかえった、金の上ぐつを持っていました。",
   "さて、サンドリヨンが出て行ったあとで、王様のお城の番小屋へ、おたずねがありました。",
   "「お<ruby>姫<rt>ひめ</rt></ruby>さまが、ひとり、門を出て行くところを見なかったか。」",
   "ところが、番兵の返事は、",
   "「はい、見たのはただひとり、ひどくみすぼらしいなりをした若いむすめでした。",
   "それは<ruby>貴婦人<rt>きふじん</rt></ruby>どころか、ただのいなかむすめとしか、おもわれないふうをしていました。」",
   "というのでした。",
   "さて、ふたりのきょうだいが、ぶとう会からかえってくると、サンドリヨンは、こういって聞きました。",
   "「たんとおもしろいことがありましたか。",
   "きれいなお姫さまは、きょうも来ましたか。」",
   "ふたりがいうには、",
   "「ああ、けれども、その人ったら、十二時を打つといっしょに、あわてて逃げだしたよ。",
   "あんまりあわてたものだから、金の<ruby>上<rt>うわ</rt></ruby>ぐつを、片足落して行ったのさ。",
   "その上ぐつの、かわいらしいことといってはないものだから、王子は、それをしまっておきなさった。",
   "王子はぶとう会でも、しじゅうお<ruby>姫<rt>ひめ</rt></ruby>さまのほうばかり見ていらしった。",
   "きっと、王子は、金の上ぐつをはいているきれいなひとを、すいていらっしゃるにちがいないよ。」",
   "なるほど、ふたりのいったとおりにちがいはありませんでした。",
   "それから二三日すると、王子はラッパを吹いておふれをまわして、その金の上ぐつの、しっくり足にはまるむすめをさがして、お妃にするといわせました。",
   "そうして、王子は、<ruby>家来<rt>けらい</rt></ruby>たちに、その金の上ぐつを持たせて、王女たちから<ruby>貴族<rt>きぞく</rt></ruby>のお姫さまたち、それから御殿じゅう、のこらずの足をためさせてみましたが、みんなだめでした。",
   "さて、とうとうまわりまわって、金の上ぐつは、いじのわるい、ふたりのきょうだいたちのところにまわって来ましたから、ふたりとも赤くなって、むりに足をつっこもうとしましたが、どうして、どうして、それはみんな、気のどくな、むだな骨おりでした。",
   "サンドリヨンは、そのとき、わきで見ていますと、それはなんのこと、じぶんの半分おとしてきた<ruby>上<rt>うわ</rt></ruby>ぐつでしたから、ついわらい出してしまって、",
   "「かしてくださらない。",
   "わたしの足にだってあうかもしれないから。」",
   "といいました。",
   "すると、ふたりのきょうだいは、ぷっと吹き出して、サンドリヨンをからかったり、あざけったり、いじわるく追いだそうとかかりました。",
   "けれど、金の上ぐつを持ったお役人は、じっとサンドリヨンの顔を見て、これはめずらしく美しいむすめだとおもいましたから、たとえ、たれでも、ためすだけは、ためしてみなければならない、それが王子様のおいいつけだといいました。",
   "そこで、サンドリヨンに腰をかけさせて、上ぐつを、その足にはかせますと、それはするりと、ぐあいよくはいって、まるでろうでかためたように、ぴったりくっついてしまいました。",
   "ふたりのきょうだいは、そのとき、どんなにびっくりしたでしょう。",
   "どうして、それどころか、サンドリヨンは、かくしの中から、もう片かたの上ぐつを出して見せました。",
   "ちょうどそのとき、サンドリヨンの<ruby>教母<rt>きょうぼ</rt></ruby>の<ruby>妖女<rt>ようじょ</rt></ruby>がすぐあらわれて、杖で、サンドリヨンの着物にさわりますと、こんどは、まえよりもまた、いっそう美しい、りっぱな着物にかわりました。",
   "それで、ふたりのきょうだいには、あのぶとう会で見た美しいお<ruby>姫<rt>ひめ</rt></ruby>さまが、サンドリヨンであったことが分かりました。",
   "ふたりは、サンドリヨンの足もとにつっぷして、これまでひどい目にあわせた<ruby>罪<rt>つみ</rt></ruby>をわびました。",
   "サンドリヨンは、ふたりの手をとっておこして、やさしくだきしめました。",
   "そして、これまでふたりのしたことは、なんともおもわない。",
   "そのかわり、これからは、やさしくしてくれるようにといいました。",
   "サンドリヨンは、りっぱな着物を着たまま、王子の前へつれて行かれました。",
   "王子は、それで、いよいよサンドリヨンがすきになって、それから四、五日して、めでたくご<ruby>婚礼<rt>こんれい</rt></ruby>の<ruby>式<rt>しき</rt></ruby>をあげました。",
   "サンドリヨンは、顔が美しいように、心のやさしいむすめでしたから、ふたりのきょうだいをも、お城へ引きとってやって、ご婚礼のその日に、やはり、ふたりの<ruby>貴族<rt>きぞく</rt></ruby>にめあわせることにしました。",
   "顔とすがたの美しいことは、男にも女にも、とうといたからです。",
   "でも、やさしく、しおらしい心こそ、妖女のこの上ないおくりものだということを知らなくてはなりません。"
  ],
  "notebook": [
   {
    "w": "わがまま",
    "read": "わがまま",
    "def": "selfish, spoiled",
    "ch": 0
   },
   {
    "w": "こうまん",
    "read": "こうまん",
    "def": "arrogant, haughty",
    "ch": 0
   },
   {
    "w": "気だて",
    "read": "きだて",
    "def": "disposition, nature",
    "ch": 0
   },
   {
    "w": "台所",
    "read": "だいどころ",
    "def": "kitchen",
    "ch": 0
   },
   {
    "w": "そうじ",
    "read": "そうじ",
    "def": "cleaning",
    "ch": 0
   },
   {
    "w": "眠る",
    "read": "ねむる",
    "def": "to sleep",
    "ch": 0
   },
   {
    "w": "あだ名",
    "read": "あだな",
    "def": "nickname",
    "ch": 0
   },
   {
    "w": "灰",
    "read": "はい",
    "def": "ash",
    "ch": 0
   },
   {
    "w": "ぶとう会",
    "read": "ぶとうかい",
    "def": "a ball, a dance party",
    "ch": 1
   },
   {
    "w": "まねく",
    "read": "まねく",
    "def": "to invite",
    "ch": 1
   },
   {
    "w": "教母",
    "read": "きょうぼ",
    "def": "godmother",
    "ch": 1
   },
   {
    "w": "妖女",
    "read": "ようじょ",
    "def": "fairy",
    "ch": 1
   },
   {
    "w": "かぼちゃ",
    "read": "かぼちゃ",
    "def": "pumpkin",
    "ch": 1
   },
   {
    "w": "馬車",
    "read": "ばしゃ",
    "def": "carriage",
    "ch": 1
   },
   {
    "w": "御者",
    "read": "ぎょしゃ",
    "def": "coachman, driver",
    "ch": 1
   },
   {
    "w": "上ぐつ",
    "read": "うわぐつ",
    "def": "slipper",
    "ch": 1
   },
   {
    "w": "十二時",
    "read": "じゅうにじ",
    "def": "twelve o'clock, midnight",
    "ch": 1
   },
   {
    "w": "王子",
    "read": "おうじ",
    "def": "prince",
    "ch": 2
   },
   {
    "w": "静まりかえる",
    "read": "しずまりかえる",
    "def": "to fall completely silent",
    "ch": 2
   },
   {
    "w": "しとやかに",
    "read": "しとやかに",
    "def": "gracefully, elegantly",
    "ch": 2
   },
   {
    "w": "名誉",
    "read": "めいよ",
    "def": "honour",
    "ch": 2
   },
   {
    "w": "あいさつ",
    "read": "あいさつ",
    "def": "greeting",
    "ch": 2
   },
   {
    "w": "時計",
    "read": "とけい",
    "def": "clock",
    "ch": 2
   },
   {
    "w": "打つ",
    "read": "うつ",
    "def": "to strike (of a clock)",
    "ch": 2
   },
   {
    "w": "お礼",
    "read": "おれい",
    "def": "thanks",
    "ch": 3
   },
   {
    "w": "のぞみ",
    "read": "のぞみ",
    "def": "wish, hope",
    "ch": 3
   },
   {
    "w": "むちゅうになる",
    "read": "むちゅうになる",
    "def": "to become absorbed/obsessed",
    "ch": 3
   },
   {
    "w": "かす",
    "read": "かす",
    "def": "to lend",
    "ch": 3
   },
   {
    "w": "ばかにする",
    "read": "ばかにする",
    "def": "to make a fool of, look down on",
    "ch": 3
   },
   {
    "w": "ことわる",
    "read": "ことわる",
    "def": "to refuse, decline",
    "ch": 3
   },
   {
    "w": "おせじ",
    "read": "おせじ",
    "def": "flattery",
    "ch": 4
   },
   {
    "w": "いましめる",
    "read": "いましめる",
    "def": "to warn, caution",
    "ch": 4
   },
   {
    "w": "あわてる",
    "read": "あわてる",
    "def": "to panic, hurry",
    "ch": 4
   },
   {
    "w": "片足",
    "read": "かたあし",
    "def": "one foot/leg",
    "ch": 4
   },
   {
    "w": "番兵",
    "read": "ばんぺい",
    "def": "guard, sentry",
    "ch": 4
   },
   {
    "w": "みすぼらしい",
    "read": "みすぼらしい",
    "def": "shabby, poor-looking",
    "ch": 4
   },
   {
    "w": "おふれ",
    "read": "おふれ",
    "def": "announcement, proclamation",
    "ch": 5
   },
   {
    "w": "家来",
    "read": "けらい",
    "def": "servant, retainer",
    "ch": 5
   },
   {
    "w": "お役人",
    "read": "おやくにん",
    "def": "official",
    "ch": 5
   },
   {
    "w": "わびる",
    "read": "わびる",
    "def": "to apologise",
    "ch": 5
   },
   {
    "w": "だきしめる",
    "read": "だきしめる",
    "def": "to embrace, hug",
    "ch": 5
   },
   {
    "w": "ご婚礼",
    "read": "ごこんれい",
    "def": "wedding",
    "ch": 5
   }
  ],
  "ideas": [
   {
    "q": "Who are the two people who treat Sandrillon (Cinderella) badly?",
    "ch": 0
   },
   {
    "q": "Where does Sandrillon have to sleep?",
    "ch": 0
   },
   {
    "q": "Why do the stepsisters call her \"Sandrillon\"?",
    "ch": 0
   },
   {
    "q": "What did the fairy godmother turn the pumpkin into?",
    "ch": 1
   },
   {
    "q": "What did she turn the six mice, the big rat, and the lizards into?",
    "ch": 1
   },
   {
    "q": "What one rule did the fairy godmother give Cinderella, and what would happen if she broke it?",
    "ch": 1
   },
   {
    "q": "What happened in the ballroom the moment Cinderella arrived?",
    "ch": 2
   },
   {
    "q": "What did Cinderella do for her stepsisters at the ball, even though they didn't recognise her?",
    "ch": 2
   },
   {
    "q": "What time did Cinderella leave the ball, and why?",
    "ch": 2
   },
   {
    "q": "What excuse does Cinderella give for seeming sleepy when her sisters get home?",
    "ch": 3
   },
   {
    "q": "What does Cinderella ask to borrow, and what is her sister's response?",
    "ch": 3
   },
   {
    "q": "Why is Cinderella secretly glad her sister refused to lend it?",
    "ch": 3
   },
   {
    "q": "Why did Cinderella lose track of time on the second night?",
    "ch": 4
   },
   {
    "q": "What did she leave behind as she ran away?",
    "ch": 4
   },
   {
    "q": "What did the guard tell the prince's messengers when they asked if he had seen a princess leave?",
    "ch": 4
   },
   {
    "q": "Why couldn't the stepsisters make the slipper fit?",
    "ch": 5
   },
   {
    "q": "How did Cinderella prove she was the mystery princess?",
    "ch": 5
   },
   {
    "q": "How does Cinderella treat her stepsisters at the end, and what does the story suggest matters more than beauty?",
    "ch": 5
   }
  ]
 },
 {
  "id": "sleeping-beauty",
  "authentic": true,
  "band": "authentic",
  "moves": {},
  "quick": [],
  "evidence": [],
  "title": "眠る森のお姫さま",
  "en": "Sleeping Beauty",
  "author": "ペロー（Charles Perrault, 1628–1703） (d. 1703)",
  "translator": "楠山正雄 (d. 1950-11-26)",
  "died": "1703",
  "card": "https://www.aozora.gr.jp/cards/001134/card43119.html",
  "orthography": "新字新仮名",
  "beyond": [
   "polite narrative past tense throughout; no classical grammar",
   "occasional long descriptive sentences with multiple clauses — good stretch practice for parsing"
  ],
  "attribution": [
   "底本：「世界おとぎ文庫（イギリス・フランス童話篇）妖女のおくりもの」小峰書店",
   "1950（昭和25）年5月1日発行",
   "※「旧字、旧仮名で書かれた作品を、現代表記にあらためる際の作業指針」に基づいて、底本の表記をあらためました。",
   "※底本では見出し「一」はページ上部に挿し絵があるため、他の見出しと字下げ分が異なっていましたが、統一しました。",
   "入力：大久保ゆう",
   "校正：秋鹿",
   "2006年1月21日作成",
   "青空文庫作成ファイル：",
   "このファイルは、インターネットの図書館、青空文庫（http://www.aozora.gr.jp/）で作られました。入力、校正、制作にあたったのは、ボランティアの皆さんです。"
  ],
  "chapters": [
   {
    "t": "第一章",
    "en": "Seven Fairies, One Curse",
    "from": 0,
    "to": 37
   },
   {
    "t": "第二章",
    "en": "The Spindle",
    "from": 38,
    "to": 91
   },
   {
    "t": "第三章",
    "en": "A Hundred Years Later",
    "from": 92,
    "to": 146
   },
   {
    "t": "第四章",
    "en": "Morning and Day",
    "from": 147,
    "to": 163
   }
  ],
  "sentences": [
   "むかしむかし、王様とお妃がありました。",
   "おふたりは、こどものないことを、なにより悲しがっておいでになりました。",
   "それは、どんなに悲しがっていたでしょうか、とても口ではいいつくせないほどでした。",
   "そのために、世界じゅうの海という海を渡って、神様を<ruby>願<rt>がん</rt></ruby>をかけるやら、お寺に<ruby>巡礼<rt>じゅんれい</rt></ruby>をするやらで、いろいろに<ruby>信心<rt>しんじん</rt></ruby>をささげてみましたが、みんな、それはむだでした。",
   "でもそのうち、とうとう信心のまことがとどいて、お妃に、ひいさまの赤ちゃんが生まれました。",
   "それでさっそく、さかんな<ruby>洗礼<rt>せんれい</rt></ruby>の式をあげることになって、お<ruby>姫<rt>ひめ</rt></ruby>さまの名づけ親になる<ruby>教母<rt>きょうぼ</rt></ruby>には、国じゅうの<ruby>妖女<rt>ようじょ</rt></ruby>が、のこらず呼び出されました。",
   "その数は、みんなで七人でした。",
   "そのじぶんの妖女なかまのならわしにしたがい、七人の妖女は、めいめい、ひとつずつ、りっぱなおくりものを持って来るはずでした。",
   "ですから、生まれたときから、お姫さまには、もうこの世でのぞめるかぎりのことで、なにひとつ身にそなわらないものはなかったのでございます。",
   "さて洗礼式がすんだあと、呼ばれた七人のなかま一同が、王様のお城にかえりますと、そこには、妖女たちのために、りっぱなごちそうのしたくが、できていました。",
   "ひとりひとりの<ruby>食卓<rt>しょくたく</rt></ruby>の上には、お<ruby>皿<rt>さら</rt></ruby>や<ruby>杯<rt>さかずき</rt></ruby>の<ruby>食器<rt>しょっき</rt></ruby>がひとそろいならべてあって、それは、大きな金の箱にはいっている、さじだの、ナイフだの、フォークだので、こののこらずが、ダイヤモンドとルビーをちりばめた、<ruby>純金製<rt>じゅんきんせい</rt></ruby>のものでした。",
   "ところで、みんなならんで<ruby>食卓<rt>しょくたく</rt></ruby>についたとき、ふと見ると、いつどこからやって来たか、たいへん年をとった妖女がひとり、のそのそと広間にはいって来ました。",
   "けれどこの妖女は、この席に呼ばれてはいなかったのです。",
   "というわけは、このおばあさんの妖女は、今から五十年もまえ、ある<ruby>塔<rt>とう</rt></ruby>の中にこもったなり、すがたをかくしてしまって、もういまでは、死んでしまっているか、<ruby>魔法<rt>まほう</rt></ruby>にでもかけられて、なにかかわったものにされてしまった、とおもわれていたからです。",
   "王様はあわてて、この妖女の前にも、ひとそろい食器を並べさせました。",
   "でも、それはもう、大きな金の箱に入れた<ruby>純金製<rt>じゅんきんせい</rt></ruby>のものではありませんでした。",
   "なにしろお客は七人のはずでしたから、七人まえのしたくしか、できてはいなかったのです。",
   "するとおばあさんの妖女は、じぶんだけが、けいべつされたようにおもって、口の中で、なにかぶつぶつ、口こごとをいっていました。",
   "そのとき、ほかの若い妖女のひとりが、そばにとなりあわせていて、おばあさんのくどくどいうことばを、そっと聞いていました。",
   "それで、このおばあさんが、王女になにかよくないおくりものをしようと、たくらんでいることがわかりましたから、食事がすんで、みんなが<ruby>食卓<rt>しょくたく</rt></ruby>から立ちあがると、そのまま、その妖女は、とばりのかげにかくれていました。",
   "それは、こうしてかくれていて、そのおばあさんが、なにをたくらもうとも、じぶんがそのあとに出て、すぐ、そののろいのことばを、うち消すようなことをいって、それをお<ruby>姫<rt>ひめ</rt></ruby>さまへのおくりものにしよう、とおもったからです。",
   "そうこうするうちに、いよいよ、妖女たちは、それぞれ、お姫さまにおくりもののことばをのべることになりました。",
   "なかで、いちばん若い妖女は、お姫さまが世界一美しい人になられますように、といいました。",
   "つぎの妖女は、天使のようなおこころがさずかりますように、といいました。",
   "三ばんめの妖女は、王女のたちいふるまいの、やさしく、しとやかにありますように、といいました。",
   "四ばんめの妖女は、たれおよぶもののないダンスの<ruby>上手<rt>じょうず</rt></ruby>になられますように、といいました。",
   "五ばんめの妖女は、<ruby>小夜啼鳥<rt>さよなきどり</rt></ruby>のような、やさしい声でおうたいになりますように、といいました。",
   "六ばんめの妖女は、どんな<ruby>楽器<rt>がっき</rt></ruby>にも、<ruby>名人<rt>めいじん</rt></ruby>の名をおとりになりますように、といいました。",
   "いよいよおしまいに、おばあさんの妖女の番になりました。",
   "この妖女は、さもいまいましそうに首をふりながら、王女は、その手を糸車のつむにさされて、けがをして死ぬだろうよといいました。",
   "このおそろしいおくりものは、身ぶるいの出るほど、みんなをびっくりさせて、たれもお<ruby>姫<rt>ひめ</rt></ruby>さまのために泣かないものはありませんでした。",
   "そのときです、若い妖女が、とばりのかげから出て来て、とても大きな声で、つぎのようなことばをいいました。",
   "「いいえ、王様、お妃様、だいじょうぶ、あなたがたのだいじなおひいさまは、いのちをおなくしになるようなことはありません。",
   "もっとも、わたくしには、この年よりのいったんかけたのろいを、のこらずときほごすまでの力はございません。",
   "おひいさまは、なるほど手のひらに、つむをおつきたてになるでしょう。",
   "けれどそのために、おかくれになるということはありません。",
   "ただ、ぐっすりと、ねこんでおしまいになって、それは百年のあいだ、目をおさましになることがないでしょう。",
   "そして、ちょうど百年めに、ある国の王子さまが来て、おひいさまの目をおさまし申すことになるでしょう。」",
   "王様は、<ruby>妖女<rt>ようじょ</rt></ruby>のおばあさんのよげんしたさいなんを、どうかしてよけたいとおもいました。",
   "そこで、その日さっそく、国じゅうにおふれをまわして、たれでも、糸車につむをつかうことはならぬ。",
   "家のうちに、一本のつむをしまっておくことすら、してはならぬ。",
   "それにそむいたものは<ruby>死刑<rt>しけい</rt></ruby>にすると、きびしくおいいわたしになりました。",
   "さてそれから、十五六年は、ぶじにすぎました。",
   "あるとき、王様とお妃様が、おそろいで、<ruby>離宮<rt>りきゅう</rt></ruby>へ遊びにお出かけになりました。",
   "そのおるすに、ある日、若い王女は、お城の中をあちこちとかけあるいておいでになりました。",
   "するうち、下のへやから上のへやへと、かけあがって行って、とうとう<ruby>塔<rt>とう</rt></ruby>のてっぺんの、ちいさなへやにはいりました。",
   "見ると、そこには、人のよさそうなおばあさんが、ひとりぼっちですわっていて、つむで糸をつむいでいました。",
   "このおばあさんは、つむを使ってはならないという、きびしい王様のおふれを、つい聞かなかったものとみえます。",
   "「おばあさん、そこでなにをしているの。」",
   "と、お姫さまはたずねました。",
   "「ああ、かわいいじょッちゃん、わたしゃ、糸をつむいでいるのだよ。」",
   "と、おばあさんはいいました。",
   "このおばあさんは、王女がたれだか、すこしも知らないようでした。",
   "「まあ。」",
   "と、王女はいいました。",
   "「なんてきれいなんでしょう。",
   "それはどういうふうにやるものなの。",
   "あたしにかしてごらんなさいな。",
   "あたしにもできるかどうか、やってみたいから。」",
   "お姫さまは、こういって、そのつむを、手にとりましたが、それは持ち方がいけなかったのか、たいへんあわてて、ぶきような持ち方をしたのか、それとも、あのわるい<ruby>妖女<rt>ようじょ</rt></ruby>ののろいのことばが、いよいよしるしをあらわすときになったのか、とたん、つむは、いきなり王女の手にささって、王女はばったり、そこに<ruby>倒<rt>たお</rt></ruby>れてしまいました。",
   "人のいいおばあさんは、あわてて人を呼びました。",
   "みんな、お城のそこからもここからも、かけ出してきました。",
   "お姫さまの顔に水をそそぎかけたり、ひもをといて着物をゆるめたり、手のひらをたたいてみたり、ハンガリア女王の水という薬で、こめかみをもんだり、いろいろにしてみても、王女は息をふきかえしませんでした。",
   "さて、王様はこのさわぎを聞いて、さっそくかけつけておいでになりました。",
   "そうして十五年むかしの<ruby>妖女<rt>ようじょ</rt></ruby>のよげんを思い出しながら、やはりこうなるうんめいだったことをさとって、お姫さまを、そのまま、お城のなかでも、いちばん上等のへやにつれて行かせ、金と銀のぬいとりをした、きれいなねだいの上にねかしました。",
   "ねだいの上に、すやすや眠っておいでになるお姫さまの、美しさといってはありません。",
   "それはちいさな天使だといってもいいくらいでした。",
   "人ごこちがなくなっていても、生きているとおりの顔いろをしていて、ほおは、せきちく色をしていましたし、くちびるは、さんごをならべたようでした。",
   "目こそつぶってはいますものの、かすかに息をする音は聞こえます。",
   "それで、王女が死んでいないということがわかったので、まわりについている人たちは、よろこんでいました。",
   "王様はそこで、やがて人が来て、目をさまさせるまで、しずかにねかしておくようにと、きびしくおいいつけになりました。",
   "さて、王女を百年のあいだ眠らせることにして、やっと、あやういいのちをとりとめた、あの心のいい妖女は、ちょうどこのさわぎの起こったとき、一<ruby>万<rt>まん</rt></ruby>二千<ruby>里<rt>り</rt></ruby>はなれた、マタカン国に行っていましたが、その使っているこびとから、この知らせをすぐうけとりました。",
   "そのこびとは、『七里とびの長ぐつ』といって、ひとまたぎに七里ずつあるく長ぐつをはいて、かけて行ったのです。",
   "それで、<ruby>妖女<rt>ようじょ</rt></ruby>はさっそくそこを出て、<ruby>竜<rt>りゅう</rt></ruby>にひかせた火の車に乗ると、ちょうど一時間で、王様のお城につきました。",
   "王様は、お手ずから、妖女を馬車から助けおろしました。",
   "妖女は、王様のなさったことを、すべてけっこうですといいました。",
   "でも、たいへん先のことのよく見える妖女でしたから、百年ののちに、お姫さまがせっかく目をさましても、この古いお城の中に、たったひとり、ぽつねんとしているのでは、どうしていいか、わからなくて、さぞお困りになるだろうと思いました。",
   "そこで、なにをしたでしょうか。",
   "妖女は、<ruby>魔法<rt>まほう</rt></ruby>の<ruby>杖<rt>つえ</rt></ruby>をふるって、王様とお妃をのぞいては、お城のなかの物のこらず、それはおつきの<ruby>女教師<rt>おんなきょうし</rt></ruby>から、<ruby>女官<rt>じょかん</rt></ruby>から、おそばづきの<ruby>女中<rt>じょちゅう</rt></ruby>から、<ruby>宮内<rt>くない</rt></ruby>官、<ruby>表役人<rt>おもてやくにん</rt></ruby>、コック長、<ruby>料理番<rt>りょうりばん</rt></ruby>から、<ruby>炊事係<rt>すいじがかり</rt></ruby>、台所ボーイ、番兵、おやといスイス兵、走り使いの<ruby>小者<rt>こもの</rt></ruby>までのこらず、<ruby>杖<rt>つえ</rt></ruby>でさわりました。",
   "それから、おなじようにして、べっとうといっしょに、うまやでねている馬も、裏庭に遊んでいるむく犬も、お姫さまのねだいの上で眠っているお手<ruby>飼<rt>がい</rt></ruby>の<ruby>狆<rt>ちん</rt></ruby>までも、みんな魔法の杖でさわりました。",
   "魔法の杖でさわると、すぐ、たれもかれも、なにもかも、たわいもなく眠りこけてしまって、お姫さまが目がさますまでは、けっして目をさましませんし、お姫さまに用事ができれば、いつでも目をさまして、御用をつとめるはずでした。",
   "なにもかも眠ってしまったといって、それはかまどの前の焼きぐしまでが、きじや、やまどりの肉をくしにさしたまま、やはり眠ってしまいました。",
   "これだけのことが、みんな、ほんの<ruby>目<rt>ま</rt></ruby>ばたきひとつするまに、できあがってしまいました。",
   "<ruby>妖女<rt>ようじょ</rt></ruby>というものは、まったくしごとの早いものですね。",
   "さてそこで、王様とお妃とは、お姫さまのひたいに、そっと、やさしくほおずりして、お城から出て行きました。",
   "そうしておいて、たれもお城に近づくことはならないという、きびしいおふれを、また国じゅうにまわしました。",
   "でも、そのおふれは、わざわざ出すまでもありませんでした。",
   "なぜというに、十五分とたたないうち、お城をとりまわしている<ruby>園<rt>その</rt></ruby>の中に、たくさんの高い木やひくい木が、もっさりと<ruby>茂<rt>しげ</rt></ruby>りだして、そのあいだには、いばらや草やぶが、びっしり<ruby>鉄条網<rt>てつじょうもう</rt></ruby>のようにからみついてしまいましたから、人間もけだものも、それをくぐってはいることはできなかったからです。",
   "そういうわけで、しばらくすると、そとから見えるものは、お城の<ruby>塔<rt>とう</rt></ruby>のてっぺんだけになりました。",
   "それも、よほど遠くにはなれてでなければ、見えないのです。",
   "これも、妖女のみごとな、はなれわざだったことがわかりました。",
   "こうして、王女は眠っているあいだ、たれひとりおもしろ半分、のぞきにくることもできないようになったのでございます。",
   "さて、百年は<ruby>夢<rt>ゆめ</rt></ruby>のようにすぎました。",
   "そのじぶん、その国をおさめていた新しい王様の王子が、ある日、眠る森の近くを通りかかりました。",
   "この王子は、眠っている王女の一<ruby>族<rt>ぞく</rt></ruby>が、とうに死にたえて、そのあとに代って来たべつの王家の王子で、その日はちょうど、そのへんに<ruby>狩<rt>かり</rt></ruby>に出かけて来たかえり道なのです。",
   "それで、遠くからお城の塔をみつけると、あの森の中にある塔はなんだといって、おそばの者にききました。",
   "みんなは、てんでん、じぶんの聞いているとおりをこたえました。",
   "なかのひとりは、あれは、ゆうれいが出るというひょうばんの、古い<ruby>荒城<rt>あれじろ</rt></ruby>だといいました。",
   "すると、またひとりが、あれはこの国の<ruby>魔法使<rt>まほうつかい</rt></ruby>や、わるいみこたちが、<ruby>夜会<rt>やかい</rt></ruby>をする場所だといいました。",
   "そのなかで、わりあい、おおぜいのもののいうところでは、あれは昔から人くい鬼の住んでいるお城で、ちいさなこどもをつかまえては、みんなあそこへさらって行って、それで、たれもあとからついてこられないように、あのとおり、じぶんだけ通って行ける森をこしらえて、その中でゆっくりたべるのだということでした。",
   "王子は、このうちのどれを信じていいか、わからないので、まよっていますと、そのとき、ひとり、この土地に古くからいる年よりのお百<ruby>姓<rt>しょう</rt></ruby>が、こういいました。",
   "「王子さま、<ruby>失礼<rt>しつれい</rt></ruby>ではございますが、わたくしが五十年も前、父から聞きました話では、――その父はまた、もとは、じじいから聞いたのだと申しますが、――このお城の中には、それはそれは美しい王女のお<ruby>姫<rt>ひめ</rt></ruby>さまが住んでおりまして、もう百年のあいだ、ずっと眠りつづけたあと、ちょうど百年めに、ある王様の王子が来て、目をさましてくださるのを、待っているのだということでございます。」",
   "若い王子は、この話を聞くと、からだじゅうに、かっとあつい血がもえあがるようにおもいました。",
   "ぜひとも、このめずらしいできごとのおさまりを、自分でつけてしまわなければとおもいたちました。",
   "美しいお姫さまをさずかるうえに、たれもはいれない<ruby>魔法<rt>まほう</rt></ruby>のお城をきりひらく<ruby>名誉<rt>めいよ</rt></ruby>が、自分のものになるとおもうと、もううしろからからだを押されるような気がして、さっそく、そのしごとにかかろうと<ruby>決心<rt>けっしん</rt></ruby>しました。",
   "そこで、王子は、森にむかってずんずん進んでいきますと、大きな木も<ruby>低<rt>ひく</rt></ruby>い木も、草やぶもいばらも、みんな道をよけて通しました。",
   "その広い道をどこまでも行きますと、やがてその<ruby>奥<rt>おく</rt></ruby>にあるお城に着きました。",
   "ところで、すこしびっくりしたことには、ふとふりかえってみると、<ruby>家来<rt>けらい</rt></ruby>に、ひとりもついてくるものがないのです。",
   "なぜというに、王子がはいるといっしょに、すぐ森の口がしまってしまったからです。",
   "けれども、王子はかまわずに、ずんずん進んでいきました。",
   "若いやさしい、そして火のようにあつい心をもった王子は、いつも勇気のあるものです。",
   "王子はやがて大きな広い庭に出ました。",
   "そこでまず見たものは、どんなこわいもの知らずでも、ぞっとして、骨までこおるようなものでした。",
   "なにもかも、<ruby>気味<rt>きみ</rt></ruby>のわるいほど、しいんとしずまりかえっていました。",
   "そこにも、ここにも、目に見えるものは、人間や動物が、みんな死んだもののように、ぐんにゃり手足をなげ出しているすがたでした。",
   "けれども、そこに立っている、おやといスイス兵の鼻いきは、ぷんとお酒くさいし、ぽおっと赤いほほをしているのを見ても、この<ruby>連中<rt>れんじゅう</rt></ruby>は、みんな眠っているのだということが、すぐ分かりました。",
   "しかも、その手にもった茶わんには、まだぶどう<ruby>酒<rt>しゅ</rt></ruby>のしずくがのこっているので、なかまとお<ruby>酒<rt>さか</rt></ruby>もりのさいちゅう、眠ってしまったのだということまで知れました。",
   "王子はそれから、<ruby>大理石<rt>だいりせき</rt></ruby>をしきつめた大ろうかを通って、かいだんの上まで行って、番兵のつめているへやにはいりますと、番兵らは<ruby>鉄砲<rt>てっぽう</rt></ruby>を肩にのせてならんだまま、ありったけの高いびきをかいてねていました。",
   "それからまた進んで、いくつかのへやを通って行きますと、どのへやにも、<ruby>紳士<rt>しんし</rt></ruby>たちや<ruby>貴婦人<rt>きふじん</rt></ruby>たちが、立っているものも、腰をかけているものも、みんな、たわいなく眠りこけていました。",
   "とうとう、おしまいにはいったのは、のこらずが金ずくめのきらきらしいへやでした。",
   "そこに、りっぱなねだいがすえてあって、四方のとばりのこらず、あげた中に、それこそこの世にふたつとない美しいものがあらわれました。",
   "たぶん十五六くらいの年ごろのお姫さまが、こうごうしく光りかがやくすがたで、眠っていたのです。",
   "あっと、おどろきながら、王子はふるえる足をふみしめふみしめ、その前にひざまづきました。",
   "さあ、これで<ruby>魔法<rt>まほう</rt></ruby>の力もいよいよつきたのでしょう、王女は、ふと目をさましました。",
   "そして、なんともいえないやさしい目で、じいっと王子のほうをながめました。",
   "「王子さま、あなたでございましたの。」",
   "と、お姫さまはそういって、にっこりしました。",
   "「ずいぶん待っていただきましたのね。」",
   "王子は、このことばを聞くと、なんといって、心のよろこびをいいあらわしていいか、分かりませんでした。",
   "王子は、じぶんのことよりも、どんなにかよけいに、お姫さまのことを、おもっているか知れないといいました。",
   "ふたりの話は、話すというよりも、泣いているといったほうがいいほど、ただもう、しどろもどろなものでした。",
   "ことばは、よどみがちでしたが、やさしい心のいずみは、かえって、いきおいよく流れ出しました。",
   "それに、王子のほうは、きまりはわるいし、ただおどろいているばかりなのに、王女のほうは、なにしろ百年のあいだ、<ruby>妖女<rt>ようじょ</rt></ruby>がおもしろい<ruby>夢<rt>ゆめ</rt></ruby>を、それからそれと見どおしに見せていてくれたのですから、いくら話しても話しても、話のたねがつきるということがないのです。",
   "ですからふたりは、かれこれ四時間もぶっとおしに話しつづけていて、そのくせ話したいことの半分も話しきらずにいました。",
   "そうこうするうち、お姫さまといっしょに、お城のそこでもここでも、みんなが目をさましました。",
   "たれもかれも、じぶんじぶんのしごとを思い出しました。",
   "ところで、みんなは、さしあたり、ほかに、くろうもくったくもありませんでしたから、まっさきにおなかがすいて、<ruby>倒<rt>たお</rt></ruby>れそうにおもいました。",
   "女官<ruby>頭<rt>がしら</rt></ruby>は、ほかの人たちとおんなじに、ひどくおなかがへって、がまんできないほどでしたから、だしぬけに大きな声で、お姫さま、お<ruby>夕飯<rt>ゆうはん</rt></ruby>のおしたくができましたと、申しあげました。",
   "王子は、王女のお姫さまを助けて立ちあがらせました。",
   "お姫さまは、ずいぶんりっぱなふうをしていましたが、なにしろそれは百年まえにはやった、王子のひいおばあさんの着物とおなじようだということを、さすがにお姫さまにむかっていうことは、えんりょしていました。",
   "いくら<ruby>流行<rt>りゅうこう</rt></ruby>おくれなふうはしていても、それがために、王女の美しさにも、かわいらしさにも、いっこう、かわりはなかったのですからね。",
   "さて、ふたりは、<ruby>鏡<rt>かがみ</rt></ruby>の<ruby>間<rt>ま</rt></ruby>に出て行きました。",
   "そこで<ruby>夕飯<rt>ゆうはん</rt></ruby>の<ruby>食卓<rt>しょくたく</rt></ruby>について、王女づきの<ruby>女官<rt>じょかん</rt></ruby>たちがお<ruby>給仕<rt>きゅうじ</rt></ruby>に立ちました。",
   "そのあいだ、バイオリンだの、<ruby>木笛<rt>きぶえ</rt></ruby>だのが、百年まえの古い<ruby>曲<rt>きょく</rt></ruby>をかなでました。",
   "それは、百年まえの古い曲にちがいありませんでしたが、りっぱな<ruby>音楽<rt>おんがく</rt></ruby>であることにかわりはありませんでした。",
   "食事がすむと、時をうつさず、<ruby>大僧正<rt>だいそうじょう</rt></ruby>は、ふたりをお城の<ruby>礼拝堂<rt>れいはいどう</rt></ruby>へ<ruby>案内<rt>あんない</rt></ruby>して、ご<ruby>婚礼<rt>こんれい</rt></ruby>をすませました。",
   "女官<ruby>頭<rt>がしら</rt></ruby>は、ふたりのためにとばりをひきました。",
   "ふたりはその晩、ほんのわずかしか眠りませんでした。",
   "王子は、あくる朝、王女にわかれて町へかえりました。",
   "おとうさまの王様が、待ちこがれておいでになるところへ、かえって行ったのでございます。",
   "王子は、<ruby>狩<rt>かり</rt></ruby>をしているうち、森の中で道にまよって、一<ruby>軒<rt>けん</rt></ruby>の炭焼小屋にとまって、チーズや黒パンをたべさせてもらったことなどを話しました。",
   "おとうさまの王様は、人のいい人でしたから、王子のいうことをほんとうになさいました。",
   "けれど、おかあさまのお妃は、もうさっそく、王子には、およめさんができていることを、おさとりになりました。",
   "それから二年たちました。",
   "王女には、ふたりもこどもが生まれました。",
   "上の子は女の子で、これは「朝」という名でした。",
   "下の子は男の子でこれは「<ruby>昼<rt>ひる</rt></ruby>」という名でした。",
   "そのわけは、弟のほうが、ねえさんよりも、ずっとりっぱで、美しかったからでございます。",
   "それからまた二年たって、王様がおかくれになって、王子が、新しい王様の位につくことになりました。",
   "そこではじめて、<ruby>天下<rt>てんか</rt></ruby>はれて、王女と<ruby>結婚<rt>けっこん</rt></ruby>のしだいを、国じゅうに知らせました。",
   "そうして、りっぱな<ruby>儀式<rt>ぎしき</rt></ruby>をととのえて、あらためて、眠る森から、お姫さまをお迎えになりました。",
   "王女はふたりのこどもを両わきにのせ、美しい行列の馬車をそろえて、王様のお城に乗りこみました。",
   "美しいりっぱな、いい心をもったあいてを、待っているということは、むずかしいことです。",
   "でも、待つことによって、幸福はましこそすれ、へるということはありません。"
  ],
  "notebook": [
   {
    "w": "お妃",
    "read": "おきさき",
    "def": "queen, queen consort",
    "ch": 0
   },
   {
    "w": "洗礼",
    "read": "せんれい",
    "def": "christening, baptism",
    "ch": 0
   },
   {
    "w": "妖女",
    "read": "ようじょ",
    "def": "fairy",
    "ch": 0
   },
   {
    "w": "おくりもの",
    "read": "おくりもの",
    "def": "gift",
    "ch": 0
   },
   {
    "w": "のろい",
    "read": "のろい",
    "def": "curse",
    "ch": 0
   },
   {
    "w": "糸車",
    "read": "いとぐるま",
    "def": "spinning wheel",
    "ch": 0
   },
   {
    "w": "つむ",
    "read": "つむ",
    "def": "spindle",
    "ch": 0
   },
   {
    "w": "けがをする",
    "read": "けがをする",
    "def": "to get hurt, injured",
    "ch": 0
   },
   {
    "w": "おふれ",
    "read": "おふれ",
    "def": "royal decree, proclamation",
    "ch": 1
   },
   {
    "w": "死刑",
    "read": "しけい",
    "def": "death penalty",
    "ch": 1
   },
   {
    "w": "塔",
    "read": "とう",
    "def": "tower",
    "ch": 1
   },
   {
    "w": "糸をつむぐ",
    "read": "いとをつむぐ",
    "def": "to spin thread",
    "ch": 1
   },
   {
    "w": "倒れる",
    "read": "たおれる",
    "def": "to collapse, fall down",
    "ch": 1
   },
   {
    "w": "よげん",
    "read": "よげん",
    "def": "prophecy",
    "ch": 1
   },
   {
    "w": "魔法の杖",
    "read": "まほうのつえ",
    "def": "magic wand",
    "ch": 1
   },
   {
    "w": "眠りこける",
    "read": "ねむりこける",
    "def": "to fall into a deep sleep",
    "ch": 1
   },
   {
    "w": "眠る森",
    "read": "ねむるもり",
    "def": "the sleeping forest",
    "ch": 2
   },
   {
    "w": "荒城",
    "read": "あれじろ",
    "def": "ruined/abandoned castle",
    "ch": 2
   },
   {
    "w": "百姓",
    "read": "ひゃくしょう",
    "def": "farmer, peasant",
    "ch": 2
   },
   {
    "w": "勇気",
    "read": "ゆうき",
    "def": "courage",
    "ch": 2
   },
   {
    "w": "しずまりかえる",
    "read": "しずまりかえる",
    "def": "to be completely silent",
    "ch": 2
   },
   {
    "w": "ひざまづく",
    "read": "ひざまづく",
    "def": "to kneel",
    "ch": 2
   },
   {
    "w": "目をさます",
    "read": "めをさます",
    "def": "to wake up",
    "ch": 2
   },
   {
    "w": "ご婚礼",
    "read": "ごこんれい",
    "def": "wedding",
    "ch": 2
   },
   {
    "w": "位",
    "read": "くらい",
    "def": "throne, rank",
    "ch": 3
   },
   {
    "w": "行列",
    "read": "ぎょうれつ",
    "def": "procession",
    "ch": 3
   },
   {
    "w": "幸福",
    "read": "こうふく",
    "def": "happiness",
    "ch": 3
   },
   {
    "w": "儀式",
    "read": "ぎしき",
    "def": "ceremony",
    "ch": 3
   },
   {
    "w": "迎える",
    "read": "むかえる",
    "def": "to welcome, receive",
    "ch": 3
   }
  ],
  "ideas": [
   {
    "q": "How many fairies were invited to the christening, and why wasn't the old fairy invited?",
    "ch": 0
   },
   {
    "q": "What curse did the old fairy place on the princess?",
    "ch": 0
   },
   {
    "q": "How did the young fairy soften the curse?",
    "ch": 0
   },
   {
    "q": "What law did the king make to try to stop the curse from coming true?",
    "ch": 1
   },
   {
    "q": "Where did the princess find the old woman spinning, and what happened when she touched the spindle?",
    "ch": 1
   },
   {
    "q": "What did the good fairy do to make sure the princess wouldn't be alone when she woke up?",
    "ch": 1
   },
   {
    "q": "What different rumours did people tell the prince about the tower in the forest?",
    "ch": 2
   },
   {
    "q": "What happened to the forest as soon as the prince walked into it?",
    "ch": 2
   },
   {
    "q": "What does the story say finally woke the princess up?",
    "ch": 2
   },
   {
    "q": "What were the names of the prince and princess's two children?",
    "ch": 3
   },
   {
    "q": "Why do you think the prince waited so long before officially announcing his marriage to the kingdom?",
    "ch": 3
   },
   {
    "q": "What does the final line of the story say about waiting for happiness?",
    "ch": 3
   }
  ]
 }
];
